### PR TITLE
Sensing Danger Micro:Pet Project

### PR DESCRIPTION
**Pull request by mrsbucksclass**

### CODE REVIEW

**Comment by pelikhan** [comment]
did you mean to create a new file or replace the existing one?

**Comment by pelikhan** [comment]
Did you use the github web site to edit the file? I think you should be able to create a new .md file in the same folder. We can help with wiring it up in the lesson. Use lower case characters and - for spaces for the file name.

**Comment by mrsbucksclass** [comment]
I’ll check it out.
Thanks,
Val

**Comment by aidancuckoo** [comment]
Hello @mrsbucksclass - Take a look at the pic I attached - it should show how to make a new file and don't worry - it should have a .md at the end by default.

**Pull request closed without merging**
