### PR TITLE
add tobbie 2

### PR DESCRIPTION
**Pull request by microbit-mark**
add tobbie II robot extension cc @kaku111

### CODE REVIEW

**Comment by pelikhan** [comment]
The package is not following MakeCode's naming conventions: https://makecode.com/extensions/naming-conventions

**Comment by pelikhan** [comment]
https://github.com/kaku111/pxt-tobbieII/issues

**Comment by microbit-mark** [comment]
Thanks for following up @pelikhan

**Comment by abchatra** [comment]
@microbit-mark I don't see a new relesae

**Comment by microbit-mark** [comment]
Have requested the user run a release

**Comment by kaku111** [comment]
Hello!!
I have increased the release from v1.0.0 to v2.0.1, and please help me to confirm that it is correct? thanks!!

newrelease

**Comment by kaku111** [comment]
I would like to ask, how to unlock and modify the approved pxt file? I want to add some languages. thanks  a lot!!

**Comment by pelikhan** [comment]
Update your repo and bump.

**Comment by kaku111** [comment]
Is there any suggested Tutorial or instruction?  thanks!!

**Pull request merged**
