### PR TITLE
Extension: add MonkMakes Plant Monitor

### PR DESCRIPTION
**Pull request by martinwork**
Arising from support ticket https://support.microbit.org/helpdesk/tickets/68299 (private)
@simonmonk
@abchatra 

https://github.com/monkmakes/plant-monitor-makecode
https://makecode.microbit.org/_XuFgDfF9kimX
image

I have mentioned the following problems:-

It might be better if "start" was called as needed by the other blocks.
https://github.com/monkmakes/plant-monitor-makecode/blob/2f92edbed33a42cc6aeee48a849adc36ecbf392c/custom.ts#L43

The README blocks example should use embedded editor elements, but it is a PNG and shows a previous version of the blocks with capitalised text. The connecting diagram is great, but it seems quite large and is 1.3MB.
https://github.com/monkmakes/plant-monitor-makecode/tree/master#readme

There are some JavaScript APIs that don't conform to https://makecode.com/extensions/naming-conventions.
https://github.com/monkmakes/plant-monitor-makecode/blob/2f92edbed33a42cc6aeee48a849adc36ecbf392c/custom.ts#L99
https://github.com/monkmakes/plant-monitor-makecode/blob/2f92edbed33a42cc6aeee48a849adc36ecbf392c/custom.ts#L107

The extension name "Plant Monitor" and namespace "PlantMonitor" also do not conform to the conventions.
https://github.com/monkmakes/plant-monitor-makecode/blob/2f92edbed33a42cc6aeee48a849adc36ecbf392c/pxt.json#L2
https://github.com/monkmakes/plant-monitor-makecode/blob/2f92edbed33a42cc6aeee48a849adc36ecbf392c/custom.ts#L13

### CODE REVIEW

**Comment by simonmonk** [comment]
This extension has been out in the wild for some time now (as an unapproved extension) so I'd really like to minimise changes such as removing the 'start plant monitor' block and replacing with a lazy-init mechanism for reasons of documentation consistency. 
I'd like to get it out as soon as possible as our customer Fair Chance Learning who want the extension approved have a deadline of early next week for a demo to a potential big customer of theirs.
I'm happy to do some polishing after that.

**Comment by martinwork** [comment]
@abchatra Do any of the issues we have noted preclude merging the PR? Is there anything we have missed?

@simonmonk Will you be able to fix these things soon?

**Comment by simonmonk** [comment]
Thanks @martinwork . Sounds like we are good to go.
Microsoft team / @abchatra -- our customer Fair Chance Learning in Canada have an urgent need for this extension. I'd really appreciate it if you could expedite the approval.

**Review by abchatra — APPROVED** [review]
I am sorry for the delay.

**Comment by abchatra** [comment]
This extension looks great.

**Pull request merged**
