### PR TITLE
Tutorial theme

### PR DESCRIPTION
**Pull request by riknoll**
Requires https://github.com/microsoft/pxt/pull/8791

Fixes https://github.com/microsoft/pxt-microbit/issues/4535
Fixes https://github.com/microsoft/pxt-microbit/issues/4534

Theming the tutorial using micro:bit editor colors. Also adding some missing file associations to the checked in vscode settings.

Screen Shot 2022-04-20 at 2 27 27 PM

### CODE REVIEW

**Review by abchatra — APPROVED** [review]

**Review by dmonroym — APPROVED** [review]

**Comment by abchatra** [comment]
Also fix the issue of arcade icon for simulator to microbit icon ?

**Comment by riknoll** [comment]
oh.... nope! will fix that also

**Comment by riknoll** [comment]
actually, I need a new icon for that. @unthinkmedia any suggestions?

**Review by jwunderl — APPROVED** [review]

**Comment by unthinkmedia** [comment]
> 

Hmm...when do you need this by?  Using the microbit icon doesn't really make sense. Maybe a play button, although it doesn't really play?

**Comment by abchatra** [comment]
This should indicate existence of simulator. May be small micobit?

**Comment by Jaqster** [comment]
I have an unpopular suggestion - don't update micro:bit to the new tutorial format.  We know there are discoverability issues with the simulator in this layout.  The benefit of this layout was to accommodate Arcade tutorials where there are lots of instructions that didn't fit in the top bar.  Micro:bit tutorial instructions are much shorter.

**Comment by abchatra** [comment]
Maintaining multiple code base for the same feature is very error prone and time consuming. I think old code is pretty much stale.
However I think we can bring back the old view in the new codebase as an option set by the target. @riknoll any idea how much that work is?

**Comment by unthinkmedia** [comment]
> This should indicate existence of simulator. May be small micobit?

A microbit is to detailed to be discernible at a small scale.  Also, I don't think a chip communicates simulator.  I would suggest we go with what Jacqueline suggested if that is feasible, and if not we might try a "play" icon.  Ultimately I would be in favor of getting rid of the tabbed pattern as it is not very discoverable and this is going to be worse with microbit since there is not mini-sim on the bottom that some kids use to get to that view.  I have some thoughts on how we might go about that if we want a more comprehensive fix.

**Comment by abchatra** [comment]
For this PR let's pick the play icon. Lets take the other things later.

**Comment by Jaqster** [comment]
Let's cost out adding a 3rd view - https://github.com/microsoft/pxt-microbit/issues/4553

**Pull request merged**
