### PR TITLE
rock paper scissors with sounds

### PR DESCRIPTION
**Pull request by pelikhan**
This is a variation on the rock paper scissor + sound. Most of the gifs are still kind of ok to reuse, but it does add one step. 
It's a fun extension.

### CODE REVIEW

**Comment by Jaqster** [comment]
I feel like we should start adding some sort of "V2 only" label on the Home Page cards...  Maybe @clkantner can help us think through a design for this...

**Comment by pelikhan** [comment]
Copied from the data logger card

**Review by ganicke — APPROVED** [review]

**Comment by pelikhan** [comment]
@Jaqster  good to go?

**Comment by Jaqster** [comment]
Yes!  We did this with the teachers yesterday, and they loved it!!!

**Pull request merged**
