### PR TITLE
experiment with screen in micro:bit

### PR DESCRIPTION
**Pull request by tballmsft**

### CODE REVIEW

**Comment by tballmsft** [comment]
Michal.

To torture myself, I am trying to put together the elements I think I need to get the screen into pxt-microbit (in advance of then pulling it out into an extension). I've made some progress but am getting some odd errors.

-- Tom

**Comment by mmoskal** [comment]
I added `disablesVariant` but now there is a name clash on Image class, which has different definition in micro:bit. 

AFAIK there is no way to rename the one in micro:bit core from an extension, and if you rename the one in game---light, your code won't work with a regular Arcade. Maybe you can define some type aliases.

The pin stuff can be probably fixed by editing the screen code directly (it goes into extension, so no need to introduce anything in common packages).

**Comment by mmoskal** [comment]
now it fails on `mixer` - I think you want to drop it and use micro:bit native sound

**Comment by tballmsft** [comment]
Yes, I thought I had removed the dependence on mixer.

**Pull request closed without merging**
