### PR TITLE
datalogger: Add CODAL flags to enable BLE service with extension.

### PR DESCRIPTION
**Pull request by microbit-carlos**
This PR adds a couple of CODAL flags to the data logging extension, so that the Utility service is enabled when bluetooth is enabled. Similarly to the Events Service.
This Utility Service is used by the iOS app to fetch and display the data logging data in the app.

Test deployment:
- https://makecode.microbit.org/app/8bb9ef7928c091a7a57aff476473c8714f4454da-1e38d1bb41

Due to this issue this PR doesn't work, so setting as a draft PR until it is resolved:
- https://github.com/microsoft/pxt-microbit/issues/5352

### CODE REVIEW

**Comment by microbit-carlos** [comment]
@abchatra this has been tested by @martinwork and ready to be merged 👍

**Comment by abchatra** [comment]
@riknoll can you review this change?

**Comment by microbit-carlos** [comment]
Apologies for the rush, but ideally we'd like to have this release as soon as possible, to be able to access the datalog from the iOS app for a specific event. Would it be possible to prioritise this? Thank you!

**Review by abchatra — APPROVED** [review]

**Comment by abchatra** [comment]
I have released the fix to live.

**Comment by microbit-carlos** [comment]
Thanks @abchatra, I appreciate it!

**Pull request merged**
