### PR TITLE
add cutebot extension

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @lionyhw

### CODE REVIEW

**Comment by pelikhan** [comment]
Is the qutebot typo by design? https://github.com/lionyhw/pxt-cutebot/blob/master/cutebot.ts#L11

________________________________

**Comment by lionyhw** [comment]
its real name is Cutebot.

**Comment by pelikhan** [comment]
Your namespace is "qutebot" -- looks like a typo.

**Comment by lionyhw** [comment]
It's my fault. It's corrected.Sorry……

**Comment by pelikhan** [comment]
I have opened a few bugs: https://github.com/lionyhw/pxt-cutebot/issues

**Comment by lionyhw** [comment]
These issues have been resolved，Is it possible to merge?

**Comment by abchatra** [comment]
@lionyhw Readme still refers to `qutebot.MotorRun`. Can you fix qutebot to cutebot?

**Comment by lionyhw** [comment]
Check again and fix it.

**Comment by lionyhw** [comment]
@pelikhan Is it possible to merge?

**Comment by pelikhan** [comment]
@abchatra

**Pull request merged**
