### PR TITLE
add Kitronik view text

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @KitronikLtd

### CODE REVIEW

**Comment by KitronikLtd** [comment]
Hi Mark,

 

Have the VIEW Text32 block we done on to Makecode micro:bit yet?  Had custom search for it and nothing appears.

The last I saw it was all good and nearly completed

 

Kind Regards

Phil Bradwell

Electronics Hardware Engineer

Tel: 0845 838 0781      Direct: 0115 988 7842   


 



 

Kitronik Ltd | Unit 12a | Glaisdale Point | Glaisdale Parkway | Nottingham | NG8 4GP 

Website <https://www.kitronik.co.uk/>  | Twitter <http://www.kitronik.co.uk/twitter>  | Facebook <http://www.kitronik.co.uk/facebook>  | YouTube <https://www.youtube.com/user/Kitronik> 

 

Kitronik Ltd is a UK registered Company (registration number 5602752)

**Comment by pelikhan** [comment]
Still waiting on fixes on your side.

**Comment by pelikhan** [comment]
Ready to merge

**Comment by microbit-mark** [comment]
fixed the merge conflict @pelikhan can this now be merged?

**Comment by microbit-mark** [comment]
Any reason why this is failing? "The command "node node_modules/pxt-core/built/pxt.js travis" exited with 20." The product is now released, so @KitronikLtd have asked for an update on the PR

**Comment by microbit-mark** [comment]
^ @pelikhan can you update? Is this waiting on any further changes?

**Comment by pelikhan** [comment]
https://github.com/KitronikLtd/pxt-kitronik-viewtext32/issues/3

**Comment by KitronikLtd** [comment]
I'm currently out of the office until the end of July and will respond to your email on my return. If your enquiry is urgent please phone the office who will locate the best person to help you.

Dave

**Comment by KitronikLtd** [comment]
Updated the block strings to be lower case and committed to github. Issue has been committed and closed

 

Kind Regards

Phil Bradwell

Electronics Hardware Engineer

Tel: 0845 838 0781      Direct: 0115 988 7842   


 



 

Kitronik Ltd | Unit 12a | Glaisdale Point | Glaisdale Parkway | Nottingham | NG8 4GP 

Website <https://www.kitronik.co.uk/>  | Twitter <http://www.kitronik.co.uk/twitter>  | Facebook <http://www.kitronik.co.uk/facebook>  | YouTube <https://www.youtube.com/user/Kitronik> 

 

Kitronik Ltd is a UK registered Company (registration number 5602752)

**Comment by pelikhan** [comment]
You need to create a new release.

**Comment by KitronikLtd** [comment]
New release created

 

Kind Regards

Phil Bradwell

Electronics Hardware Engineer

Tel: 0845 838 0781      Direct: 0115 988 7842   


 



 

Kitronik Ltd | Unit 12a | Glaisdale Point | Glaisdale Parkway | Nottingham | NG8 4GP 

Website <https://www.kitronik.co.uk/>  | Twitter <http://www.kitronik.co.uk/twitter>  | Facebook <http://www.kitronik.co.uk/facebook>  | YouTube <https://www.youtube.com/user/Kitronik> 

 

Kitronik Ltd is a UK registered Company (registration number 5602752)

**Pull request merged**
