### PR TITLE
Extension: add wait blocks

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @TeacherPinky

### CODE REVIEW

**Review by TeacherPinky — APPROVED** [review]

**Comment by abchatra** [comment]
@TeacherPinky Nice set of blocks. 

Quick question I see main.blocks file in the pxt.json. Does it need to be there? If not remove it from the list of files to be served? 
    "files": [
        "main.blocks",
        "README.md",
        "waitUntil.ts"
    ],

**Comment by TeacherPinky** [comment]
.@abchatra. Thanks!

I didn't take a close look at the pxt.json file before, because I think it
was automatically generated from the MakeCode blocks editor for the
micro:bit. I removed "main.blocks" as you suggested, but then the extension
didn't work anymore in Edge and therefore I added main.blocks again. Is
that okay for you?

Kind regards,

Martine

Op di 28 sep. 2021 om 23:01 schreef Abhijith Chatra <
***@***.***>:

**Comment by TeacherPinky** [comment]
Hi, I just noticed the checks that were not successful. I am sorry that I didn't see them before, when I replied to the email I received. Do you want to do those checks again after I removed "main.blocks" from the list you refer too and then we'll check again later whether it still works in Edge?

**Comment by abchatra** [comment]
There were some conflicts. I resolved them. 

This extension looks good. I will merge it.

**Comment by TeacherPinky** [comment]
> There were some conflicts. I resolved them.
> 
> This extension looks good. I will merge it.

Thank you very much!

**Pull request merged**
