### PR TITLE
Change "on-board" speaker to "built-in"

### PR DESCRIPTION
**Pull request by livcheerful**
fixes https://github.com/microsoft/pxt-microbit/issues/3600

The docs also weren't working for this block, so I fixed the path for that. Question - should I be able to test the docs locally?

### CODE REVIEW

**Review by pelikhan — APPROVED** [review]

**Comment by pelikhan** [comment]
The original extension used the "on board" name so our api was backward compatible; we should add a update rule to convert the old name to the current one. Otherwise looks great.

**Review by pelikhan — APPROVED** [review]

**Comment by livcheerful** [comment]
> The original extension used the "on board" name so our api was backward compatible; we should add a update rule to convert the old name to the current one. Otherwise looks great.

oooooooh okay cool good to know I'll do that

**Review by jwunderl — APPROVED** [review]
You should be able to check the docs locally; http://localhost:3232/reference/music/set-built-in-speaker-enabled and the 'help' for the block should both show up~

**Comment by livcheerful** [comment]
> The original extension used the "on board" name so our api was backward compatible; we should add a update rule to convert the old name to the current one. Otherwise looks great.

Question -- was the original extension only supported with beta?

**Comment by pelikhan** [comment]
Yes 3.0 and above.

________________________________

**Pull request merged**
