### PR TITLE
Split MakerBit extension into stand-alone packages

### PR DESCRIPTION
**Pull request by philipphenkel**
@microbit-mark @abchatra We split our approved MakerBit extension into stand-alone extensions. This way we are more memory efficient and allow for easy re-use of our modules even when users do not have our board. 
The "master" extension still exists and includes our modules as dependencies (BT disables as a compromise).

### CODE REVIEW

**Comment by microbit-mark** [comment]
These look good to me @abchatra

**Comment by abchatra** [comment]
Sorry for the bit delay. @philipphenkel Is this good to merge?

**Comment by philipphenkel** [comment]
@abchatra Yes, looks good from my perspective.

**Comment by pelikhan** [comment]
@philipphenkel please check that the examples in your README.md compile.

**Comment by philipphenkel** [comment]
@pelikhan Thanks for the merge! I will check all example code today.

**Pull request merged**
