### PR TITLE
[Stable3.0] Docs cherry picks

### PR DESCRIPTION
**Pull request by jwunderl**
cherry-picking docs changes to release branch, so electron release can get up to date docs.

All changes under /docs, besides:

* targetconfig.json updating approved extensions to match with updated docs/extensions, and removing beta header
* playlist.json is for referencing the playlists on the homescreen, just a header update.

makes stable up to date with docs changes through https://github.com/microsoft/pxt-microbit/commit/3495ce837653fa42f041f51dd7da3bca9f384d0b

### CODE REVIEW

**Comment by abchatra** [comment]
Porting extensions are not necessary right? We pick the latest targetconfig by last change

**Comment by jwunderl** [comment]
the targetconfig portion wouldn't be necessary from the last change I made on electron side, but each of extension adding commits also updates docs/extensions so omitting them would cause merge conflicts; I was going to drop the docs/extensions update except there was a big reordering here: https://github.com/microsoft/pxt-microbit/pull/3215 that seemed worth including.

If you'd prefer I can remove those ones and drop the docs/extension change from this pr ~

**Comment by abchatra** [comment]
Nope looks good. I was just asking.

**Comment by abchatra** [comment]
Merge it

**Pull request merged**
