### PR TITLE
enable radio programs in multi

### PR DESCRIPTION
**Pull request by pelikhan**
Enabling multi-editor "hot-or-cold" tutorial + tile to open multi-editor.

### CODE REVIEW

**Comment by ganicke** [comment]
New path spec for SxS: `:|:`?

**Comment by pelikhan** [comment]
yes it separate the path for each frame.

**Comment by abchatra** [comment]
Following launches two tutorial side by side. It doesn't make sense when you follow the steps.

https://makecode.microbit.org/---multi#tutorial:/projects/hot-or-cold/beacon:|:tutorial:/projects/hot-or-cold/seekers

Hot & Cold is one of the top tutorial, please fix this asap. @pelikhan

**Comment by abchatra** [comment]
I think I know the issue.  Seekers should be on the left side & beacon on the right. There is lot more context on seeker instead of beacon.

**Comment by pelikhan** [comment]
Do you want me to revert to single tutorial or to swap the dual tutorials?

________________________________

**Pull request merged**
