### PR TITLE
Stop all sounds

### PR DESCRIPTION
**Pull request by pelikhan**
Support for stopping sound expressions; e.g. button smashing a button and restarting the sound ASAP.

Untested on HW.

### CODE REVIEW

**Comment by abchatra** [comment]
Does this also stop tones like 'play tone' & 'ring tone'?

**Comment by pelikhan** [comment]
Yes ``rest(0)`` should stop those.

**Review by abchatra — APPROVED** [review]
Looks good to me. Can you share the screenshot of the blocks? Does 'sounds' category come before 'melody advanced'? Should this be just part of 'Volume' category?

**Comment by pelikhan** [comment]
Well we need to decide where to put it. I have it right under "play melody" right now.

**Review by jwunderl — APPROVED** [review]
I think I'd vote for putting it as the last block under the volume group? That's where I'd start looking for it.

**Review by livcheerful — APPROVED** [review]
I like Joey's suggestion of in the Volume category -- under the Melody Advanced category with the "stop melody all" would also make sense to me. Then you're forced to ask yourself what the difference is

**Comment by pelikhan** [comment]
Moved to volume.

**Pull request merged**
