### PR TITLE
Support for HID-based partial super-fast flashing

### PR DESCRIPTION
**Pull request by mmoskal**
This uses DAP.js (specifically, [my fork](https://github.com/mmoskal/dapjs) or [ARM's rewrite](https://github.com/ARMmbed/dapjs) of [my initial implementation](https://github.com/Microsoft/dapjs)) to perform flashing over HID, via the DAP (debugger) interface.

Typical flashing time is 600-800ms.

Requires https://github.com/Microsoft/pxt/pull/2842

### CODE REVIEW

**Comment by pelikhan** [comment]
@jaustin what is a sustainable story for dap.js? We don't want tons of versions flying around.

**Comment by pelikhan** [comment]
Works great!

**Comment by abchatra** [comment]
I have filed oss request for https://ossmsft.visualstudio.com/_oss?requestId=52806&_a=progress

**Comment by pelikhan** [comment]
@abchatra can we merge this?

**Comment by abchatra** [comment]
Yes good to go. OSS request is approved from Microsoft legal. 

Only comment legal had was the https://github.com/ARMmbed/dapjs  repo should update the right MIT license file in their root folder. I understand, it is up to them (@jaustin)

**Pull request merged**
