### PR TITLE
Target docs and images for 'identity' and 'share' pages

### LINKED ISSUE #5366: Update the 'identity' and 'share' docs
Hi Galen,
Would like to update 3 doc pages - 
- [ ] Online Accounts https://makecode.microbit.org/identity/sign-in
[Microbit - Online Accounts.docx](https://github.com/microsoft/pxt-microbit/files/12825633/Microbit.-.Online.Accounts.docx)

- [ ] Cloud Synch https://makecode.microbit.org/identity/cloud-sync
[Microbit - Cloud Synchronization.docx](https://github.com/microsoft/pxt-microbit/files/12825636/Microbit.-.Cloud.Synchronization.docx)
ProjectCards
Saving
CloudProjects

- [ ] Sharing Projects https://makecode.microbit.org/share
[Microbit - Sharing your project.docx](https://github.com/microsoft/pxt-microbit/files/12825640/Microbit.-.Sharing.your.project.docx)
UpdateLink
AnonShareLink
EditSharedProject
PersistShareLink
ReportAbuse
ShareEmbed
ShareIcon
ShareLMS
ShareProject
ShareQRCode
ShareTeams

Can you also make entries for these pages in the documentation [Table of Contents](https://makecode.microbit.org/docs)?  Maybe under Miscellaneous?
image

Thanks!
Jacqueline

### PR DESCRIPTION
**Pull request by ganicke**
Target specific images for the 'Identity' and 'Share' pages update.

Depends on https://github.com/microsoft/pxt/pull/9713

Closes #5366

### CODE REVIEW

**Review by Jaqster — APPROVED** [review]
Thanks Galen!

**Comment by ganicke** [comment]
Seems that `pxt checkdocs ` is missing something. The `/homepage-content` link should be valid.

image

image

**Comment by Jaqster** [comment]
@abchatra - do you know why this is failing?

**Comment by abchatra** [comment]
Seems like passed now?

**Comment by ganicke** [comment]
No, I took it out of the extended SUMMARY for now. Isn't the build pulling HEAD?

**Comment by abchatra** [comment]
@riknoll ?

**Pull request merged**
