### PR TITLE
Extensions: add HuskyLens

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @tangjie133

### CODE REVIEW

**Comment by microbit-mark** [comment]
pending rename of huskylens.png > icon.png

**Comment by tangjie133** [comment]
Icon name has been modified.

**Comment by tangjie133** [comment]
Hi Mark,
The name of the icon has been modified, but I don't understand the problems in the following detection. What's the matter.



Best Regards,

Tang








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mark"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 晚上8:09
收件人:&nbsp;"microsoft/pxt-microbit"<pxt-microbit@noreply.github.com&gt;;
抄送:&nbsp;"知音少，断弦有谁听"<1334875503@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/pxt-microbit] Extensions: add HuskyLens (#3209)





 
pending rename of huskylens.png &gt; icon.png

**Comment by abchatra** [comment]
@tangjie133 I am sorry for the delay in the review of the extension. Extension looks good. 

Couple of comments on the blocks to make it easy for the students to understand

- You could drop HuskyLens word from every block.  Category is already named as HuskyLens and this would shorten the length of the block 
- You could drop _get from result_ from many blocks. Like _HuskyLens get from result studyed ID_ can just be _study ID_
_ There is a typo in _Studyed ID_, should this be just _Study ID_? 
- If possible remove initialize blocks and do auto initialization as part of your extension initialization

image

**Comment by abchatra** [comment]
Comments are to improve the experience of a student to better understand these blocks. Otherwise extension looks good.

**Comment by tangjie133** [comment]
@abchatra I'm not sure how to do the last one.

**Comment by tangjie133** [comment]
@abchatra  Hi, abchatra, I'm sorry, the module name and function in makecode library can't be modified now, because we have written many tutorials for huskylens. If you modify the library, the tutorials will not match. Please forgive me

**Comment by abchatra** [comment]
No worries, these are suggestion any way

**Comment by abchatra** [comment]
I will merge the changes tomorrow

**Comment by tangjie133** [comment]
thank you

**Pull request merged**
