### PR TITLE
Extensions: Add Inksmith Climate Action Kit

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @dugbraden

### CODE REVIEW

**Comment by microbit-mark** [comment]
@dugbraden PLease can you run a release https://github.com/dugbraden/pxt-climate-action-kit/releases with `pxt bump` in the CLI or using the Github integration.

**Comment by dugbraden** [comment]
Done, thanks Mark!

**Comment by pelikhan** [comment]
Release number should be ``vMAJOR.MINOR.PATCH``, e.g ``v1.0.0``. If you import the repository in https://makecode.microbit.org/beta, go to the beta view and click "create release" to create a release with the proper format.

**Comment by dugbraden** [comment]
Done! Thanks Peli.

**Comment by pelikhan** [comment]
@dugbraden you need to rename the icon to "icon.png"

**Comment by dugbraden** [comment]
> @dugbraden you need to rename the icon to "icon.png"

done!

**Pull request merged**
