### PR TITLE
Don't calibrate compass while querying magnetic force.

### PR DESCRIPTION
**Pull request by abchatra**
Fixes https://github.com/microsoft/pxt-microbit/issues/4995

### CODE REVIEW

**Comment by abchatra** [comment]
This also moves compass api higher and together

image

**Review by jwunderl — APPROVED** [review]
👍

**Comment by Jaqster** [comment]
Will this require a change to the Compass tutorial?  
https://makecode.microbit.org/#tutorial:/projects/compass
https://makecode.microbit.org/_c872uoY7ob5F
Will they need to add a Calibrate block?

**Comment by abchatra** [comment]
Above tutorial only uses "compass heading" which still does calibration and no changes required.

**Comment by abchatra** [comment]
@ganicke can you take a look at this and see if any tutorial need update? 
https://github.com/search?q=repo%3Amicrosoft%2Fpxt-microbit%20magneticForce&type=code

**Comment by abchatra** [comment]
Basically magnetic force api doesn't do calibration automatically and might have issues if a tutorial is measuring earths magnetic force. So we will need to add calibrate block explicitly in such tutorials.

**Pull request merged**
