### PR TITLE
Markdown codecard conversions

### LINKED ISSUE #4036: migrate to markdown docs cards
The new pxt version comes with markdown-based support for card lists instead of json. The new format is compatible with crowdin -- unlike the current json.

### PR DESCRIPTION
**Pull request by ganicke**
Convert all ```` ```codecard```` sections from the old JSON format to the newer text, name-value form.

@pelikhan - the auto-create for `./docs/projects.md` needs an update to use the new codecard format.

Closes #4036

### CODE REVIEW

**Review by pelikhan — APPROVED** [review]
Someone from the MakeCode team should also validate this. This will help greatly with translations of those pages.

**Comment by pelikhan** [comment]
> @pelikhan - the auto-create for ./docs/projects.md needs an update to use the new codecard format.

@abchatra pxt CLI needs a little upgrade there.

**Comment by ganicke** [comment]
A small "BTW" detail is that the last item also needs the `---` delimiter as it's last line to get included in the list.

**Comment by ganicke** [comment]
Once this checks out, go ahead and convert the codecards in Arcade and Minecraft too?

**Comment by abchatra** [comment]
>> Once this checks out, go ahead and convert the codecards in Arcade and Minecraft too?

Arcade yes. Minecraft needs to wait as we haven't released any update in a while.

**Review by jwunderl — APPROVED** [review]
LGTM

**Comment by ganicke** [comment]
Fingers crossed. This has the potential to break the home screen if not more.

**Pull request merged**
