### PR TITLE
Salute! math game, classroom activity

### PR DESCRIPTION
**Pull request by ganicke**
The **Salute!** math game adapted from Vicky Sedgwick's mail and reference:

https://docs.google.com/document/d/1FAGRwEDmgKUICigkQEtuRwh3EiUFwD63xS0Lm7B-lVc/edit

This is structured as a classroom activity, keep the referrals to "students" or change to  strictly "players"? Also, attribution required?

### CODE REVIEW

**Comment by pelikhan** [comment]
Let’s ask her about attribution.

**Comment by pelikhan** [comment]
I prefer player so good.

**Comment by Jaqster** [comment]
I just asked her for permission and to review

**Comment by ganicke** [comment]
https://makecode.microbit.org/projects/salute

**Pull request merged**
