### PR TITLE
Added Electric guitar using Microbit project documentation in docs

### PR DESCRIPTION
**Pull request by akshitagupta15june**
issue #4818 

Project using micro:bit

->Added code.md as well as make.md

->A youtube video for final project

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
@riknoll please review

**Comment by akshitagupta15june** [comment]
@riknoll @jwunderl please review

**Comment by akshitagupta15june** [comment]
@ganicke please review

**Comment by ganicke** [comment]
@akshitagupta15june - Sorry that I didn't see the earlier review request. I'll will take a look at it tomorrow.

**Comment by ganicke** [comment]
Please add these images in a folder created at: `./docs/static/projects/electric-guitar`

connections

guitar-board1


guitar-board2

**Review by ganicke — CHANGES_REQUESTED** [review]
See the changes listed in the previous comment.

**Comment by akshitagupta15june** [comment]
Thankyou so much @ganicke for reviewing, I have made the required changes.
image

**Comment by ganicke** [comment]
@akshitagupta15june - We don't need a `readme.md` with the images so I removed that. Hey, are you good at art? We'll need a thumbnail image to put in a 'card' for your project in the home screen gallery:

image

It can be drawn in the same "comic" style as the other Music projects. The image is uploaded just to `./docs/static/mb/projects` folder. See `./docs/projects/music.md` for reference. Your project will go in as the fourth entry in the gallery list.

Thanks!

**Comment by akshitagupta15june** [comment]
So i will make a icon for it but do i have to add the image in docs/static/mb/projects or just have to send here

**Comment by akshitagupta15june** [comment]
Hey @ganicke so I tried making a doodle just like what my electric guitar look like 
image

**Comment by akshitagupta15june** [comment]
let me know if anything more is required for this pr! @ganicke

**Comment by ganicke** [comment]
@akshitagupta15june - now, if you can upload this image and save it to your branch as `./docs/static/mb/projects/electric-guitar.png` (it's skewed some since we need it as a 300x200 thumbnail), we can finish and publish this project. Thanks.

image

**Comment by akshitagupta15june** [comment]
@ganicke done! 

Thankyou

**Comment by akshitagupta15june** [comment]
@ganicke i also updated the code.md because it had make.md link as /docs/projects---->/projects/electric-guitar

**Review by ganicke — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
Thankyou so much @ganicke  for approving my pull request, its my first pr in microsoft repo, I would like to contribute more projects in this repo in future.

**Comment by ganicke** [comment]
@akshitagupta15june - you might experiment with the new `play sound` block and see if that might give even more realism to the  guitar sounds.

**Comment by akshitagupta15june** [comment]
cool! I will see to it

**Comment by akshitagupta15june** [comment]
hey @ganicke I can't see the project in the official makecode website will it visible after a new release or something?

**Comment by akshitagupta15june** [comment]
hey @ganicke the picture is not visible
image

**Comment by ganicke** [comment]
@akshitagupta15june - correct. I need the PNG in the folder specified in comment: https://github.com/microsoft/pxt-microbit/pull/4819#issuecomment-1247335581

**Pull request merged**
