### PR TITLE
add micro:rover

### PR DESCRIPTION
**Pull request by microbit-mark**
add Freenove micro:rover from https://github.com/Freenove/Makecode-Extension-Rover

cc @SuhaylZhao

### CODE REVIEW

**Comment by abchatra** [comment]
I filed some issues for this package.  License one needs to be fixed https://github.com/Freenove/Makecode-Extension-Rover/issues

**Comment by SuhaylZhao** [comment]
> I filed some issues for this package. License one needs to be fixed https://github.com/Freenove/Makecode-Extension-Rover/issues

Hi，

Thank you for your work. I've changed them. Please check it.

Thanks again.

**Comment by pelikhan** [comment]
https://github.com/Freenove/Makecode-Extension-Rover/issues/3

**Comment by SuhaylZhao** [comment]
> [Freenove/Makecode-Extension-Rover#3](https://github.com/Freenove/Makecode-Extension-Rover/issues/3)

Hi,

Thanks for your work. I've changed the color of all the blocks to the same color. Please check it.

Thanks again.

**Comment by microbit-mark** [comment]
Looks like the issues have been fixed @abchatra

**Pull request merged**
