### PR TITLE
Extension: add Craft & Code

### PR DESCRIPTION
**Pull request by martinwork**
Arising from https://support.microbit.org/helpdesk/tickets/83994 (private)
@KitronikLTD
@abchatra 

Extension: https://github.com/KitronikLtd/pxt-kitronik-Craft-and-Code/
All blocks: https://makecode.microbit.org/_R8ib512Y2bkt

image

### CODE REVIEW

**Comment by abchatra** [comment]
@martinwork that seems good way to me. Other hardware specific API are deviceSerialNumber, hardwareVersion etc. But harder to parse on what is for hardware and what is not.

**Comment by martinwork** [comment]
Thanks @abchatra !

**Comment by abchatra** [comment]
@martinwork  is this good to merge or are we waiting on this?

**Comment by martinwork** [comment]
@abchatra I think we can go ahead. @KitronikLtd have the deviceName fix ready in a branch.
https://github.com/KitronikLtd/pxt-kitronik-Craft-and-Code/tree/v1.0.3

**Review by abchatra — APPROVED** [review]

**Pull request merged**
