### PR TITLE
Update nexus:bit entry 

### PR DESCRIPTION
**Pull request by microbit-mark**
As per https://github.com/microsoft/pxt-microbit/pull/2043#issuecomment-513660069 the original author of this extension leaving the company and as such is requesting the extension is moved it to an organisational repository.

### CODE REVIEW

**Comment by alankrantas** [comment]
Hi. Is the PR good to go? Sorry to ask but my boss is waiting for this.

**Comment by microbit-mark** [comment]
@pelikhan I have permission to merge commits, are you happy for me to do this for extensions?

**Comment by pelikhan** [comment]
No.

________________________________

**Comment by alankrantas** [comment]
Thank you guys!

**Pull request merged**
