### PR TITLE
Bumped CODAL version to v0.2.63

### PR DESCRIPTION
**Pull request by JohnVidler**
Bumping CODAL to v0.2.63, with patches for some memory and sleep errors.

Changelog: https://github.com/lancaster-university/codal-microbit-v2/blob/master/Changelog.md

### CODE REVIEW

**Comment by microbit-carlos** [comment]
Test deployment:
- https://makecode.microbit.org/app/0194366e0b1cfb6723ca9a61571430839a7caec6-b5644b7ab3

@martinwork could you give this a quick test to confirm the issue with the display pins from https://github.com/microsoft/pxt-microbit/issues/5371 is resolved in this MakeCode instance?

**Comment by martinwork** [comment]
@microbit-carlos The display pins are back as before.

**Comment by microbit-carlos** [comment]
Awesome, thanks @martinwork!

@abchatra this is ready to be merged 👍

**Review by abchatra — APPROVED** [review]

**Comment by abchatra** [comment]
@martinwork @carlosperate  can you also test /stable with the ported fix of this codal update? (Ensure version 6.0.21)? 

If the bits are stable please signoff this PR: https://github.com/microsoft/pxt-microbit/pull/5394

**Comment by martinwork** [comment]
@abchatra @microbit-carlos Test project: https://makecode.microbit.org/_Ag3iyVAq4M4P

The LED pins seem to be working as expected in /stable.

image

**Comment by microbit-carlos** [comment]
@abchatra I believe this has been pushed to beta, but not live, is that correct?

**Comment by abchatra** [comment]
Yes it is in /stable and will release as soon as the customer responds.

**Pull request merged**
