### PR TITLE
Extensions: add HX711 weight sensor

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @daferdur

### CODE REVIEW

**Comment by abchatra** [comment]
@daferdur overall looks good.

Couple of comments:
1. It is good to avoid acronym in the blocks like DOUT and PD_SCK. Blocks are supposed to be student friend. If you could expand them to readable things that would be great. 

2. Your pxt.json need to include any images you  refer in readme.md. As readme.md is rendered as help once the extension is approved. Something like this: https://makecode.microbit.org/pkg/microsoft/pxt-neopixel
Make sure those images are <100kb to avoid network issues.

Let me know if you have nay questions.

**Comment by daferdur** [comment]
Ok, let me improve it in a few days.
Thanks.

**Comment by daferdur** [comment]
Hi Abhijith,

I've done some improvements as you mentioned.
Hope it will serve.

Regards.

**Comment by abchatra** [comment]
Looks great. Thank you!

**Pull request merged**
