### PR TITLE
Extension: Add hackbit

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @HackidsEdu

### CODE REVIEW

**Comment by abchatra** [comment]
@HackidsEdu Is this extension working? I am getting >64k error and it is not loading.

**Comment by HackidsEdu** [comment]
> @HackidsEdu Is this extension working? I am getting >64k error and it is not loading.

Hi @abchatra , local, I'm using it with v1 and v2. 
I just posted a video on our instagram using V1 as RC and V2 in the robot.
I'll check.

**Comment by HackidsEdu** [comment]
@HackidsEdu Is this extension working? I am getting >64k error and it is not loading.
@abchatra , I can eliminate three entries in pxt.json to reduce the size.

**Comment by abchatra** [comment]
Yes please, if the code is not required in the extension you should remove it. However these are valid code let me know as well.

**Comment by HackidsEdu** [comment]
> Sim, por favor, se o código não for necessário na extensão, você deve removê-lo. No entanto, esses são códigos válidos, informe-me também.

@abchatra , removed ( pxt.json and .ts files).
I hope it solves. :)

**Comment by abchatra** [comment]
You need to add github tag as well. This is still not loading for me

You can try by searching the entire github url in the search bar
image

**Comment by HackidsEdu** [comment]
> You need to add github tag as well. This is still not loading for me
> 
> You can try by searching the entire github url in the search bar image

@abchatra Can you help me where I'm going wrong?
I added it to readme.md
and added a release tag.
I'm on the slack (U01CH5HAZPU).
01-git

**Comment by HackidsEdu** [comment]
Hi @abchatra , @microbit-mark  

I am having this error.
Do I need to change something in the repo (git)?

error

**Comment by abchatra** [comment]
This is because the file size is still above 64k
image

Do you need all the code in all these files? If not remove them from pxt.json? 

If you need it every part of these code, let me know. I will try to see what can be done from our end.

**Comment by abchatra** [comment]
This is particularly complaining about hackbit.ts. As a workaround you could try splitting that file into 2 as well.

**Comment by HackidsEdu** [comment]
> This is particularly complaining about hackbit.ts. As a workaround you could try splitting that file into 2 as well.

Tks @abchatra , golden tip.
I think everything is 'ok' now. :)

image

**Comment by abchatra** [comment]
Great. 

@HackidsEdu  few comments; 

-  Can you remove unwanted files like [_locale folder](https://github.com/HackidsEdu/pxt-hackbit/tree/master/_locale)? Locales is the right folder and you have it too.

I am still reviewing and will get back with more comments if need be.

**Review by abchatra — APPROVED** [review]

**Comment by abchatra** [comment]
I have merged this. I don't have any other comments.

**Pull request merged**
