### PR TITLE
Pisupply

### PR DESCRIPTION
**Pull request by microbit-mark**
Add @PiSupply as approved organisation.

They have acknowledged that on approval they will:
 - submit their own PRs to update the gallery
 - tag beta packages in the repo description
 - hide packages in development from pxt-microbit

@jaustin fyi

### CODE REVIEW

**Comment by microbit-mark** [comment]
Not a new policy @pelikhan, we just haven't added an organisation since Seeed in January.

**Comment by pelikhan** [comment]
There are several issues with each package: icon too large, no releases, not following typescript naming conventions. It is better for quality to validate each package until the .org is trained.

**Comment by ryanteck** [comment]
pxt-lora-node should be sorted out now from what I can tell.

pxt-bitbuggy will be done within a day.

**Comment by pelikhan** [comment]
This needs to go in v1 to be active... or wait next week.

**Comment by shawaj** [comment]
thanks all :-)

**Pull request merged**
