### PR TITLE
Update Docs Reference grammar

### PR DESCRIPTION
**Pull request by billbogaiv**
Standardizes title and parameter grammar (capitalization and periods mostly).

### CODE REVIEW

**Comment by billbogaiv** [comment]
There's a lot more (at least with the reference pages) that don't follow the camel-case title convention than do. So, the expected convention for titles is camel-case with spaces?

**Comment by ganicke** [comment]
Yes, that's correct (camel-case with spaces). Thanks for scanning through them and helping with a cleanup!

**Comment by billbogaiv** [comment]
@ganicke: I went through all the ref. pages and made the titles consistent.

A few pages were left alone since they were regular docs. pages and not for specific methods.

**Comment by ganicke** [comment]
@pelikhan, OK with the risk level on this merge? It's a lot of files but a lot good minor cleanups.

**Comment by pelikhan** [comment]
I don't think it is worth it. We need to assess how many translations we are destroying.

**Comment by ganicke** [comment]
OK. In the minimum it would at least break all those page titles.

**Comment by pelikhan** [comment]
We can enfore capitalization via CSS.

**Pull request closed without merging**
