### PR TITLE
Temp revert code card conversion

### PR DESCRIPTION
**Pull request by jwunderl**
re: https://github.com/microsoft/pxt-microbit/issues/4300, reverts

* https://github.com/microsoft/pxt-microbit/pull/4301
* https://github.com/microsoft/pxt-microbit/pull/4298
* https://github.com/microsoft/pxt-microbit/pull/4288

After this is in we can try to do it piecemeal and identify why it's currently breaking

### CODE REVIEW

**Review by abchatra — APPROVED** [review]

**Comment by ganicke** [comment]
Do we want to try this conversion again but with just a few pages at a time?

**Comment by jwunderl** [comment]
If you want to try 1 gallery at a time we can try it, it's still not clear / I'm checking with their side but it sounds like it's possible it will fix itself if we re upload. It's easy to verify once the build goes through whether it will work or not (see screenshots from https://github.com/microsoft/pxt-microbit/issues/4300) so I'm happy to review if you want to go through it, otherwise I'll find some time to get them updated eventually

**Comment by ganicke** [comment]
This might require a manual review and properly applying the translations in the right places after the upload. Initially, we could do the gallery related pages and perform a manual pass to apply the proper translations?

**Comment by pelikhan** [comment]
I'd try with one gallery. Possible a copy of an existing one to test things out; then pick a gallery way down the bottom of the home screen.

**Comment by ganicke** [comment]
Turtle will be our home screen test victim.

**Pull request merged**
