### PR TITLE
add dfplayer mini extension

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @xuefengedu

### CODE REVIEW

**Comment by xuefengedu** [comment]
Thanks Mark!

**Comment by xuefengedu** [comment]
Hello @abchatra @pelikhan, can you help to review this PR? thanks very much for your great help!

**Comment by xuefengedu** [comment]
Hello @abchatra & @pelikhan, can you help to review this PR? thank you!

**Comment by pelikhan** [comment]
Filed issues on your repo https://github.com/51bit/dfplayermini/issues

**Comment by xuefengedu** [comment]
@pelikhan thanks for reviewing! I am fixing it.

**Comment by xuefengedu** [comment]
@pelikhan I have fixed the issues, can you help to approve it? thank you!

**Pull request merged**
