### PR TITLE
Extension: add Joy-IT Joy-Pi Advanced

### PR DESCRIPTION
**Pull request by martinwork**
Arising from https://support.microbit.org/helpdesk/tickets/62381 (private)

@jxns
@abchatra 

https://makecode.microbit.org/_VtcagWabsHfP
joypi-advanced

### CODE REVIEW

**Comment by abchatra** [comment]
This extension looks good. However one suggestion I see lot of subcategories with each having just a few blocks. May be better to combine them to fewer subcategory? In the same category you can have sub headings to differentiate.

image

Sub headings

image

**Comment by jxns** [comment]
Thank you, I was not aware of the subheadings feature. Do you have a link for that?
There are indeed a lot of subcategories but we wanted to distinguish every single module from each other. But we will consider changing this for a better overview.
Is this mandatory for an approval?

**Comment by martinwork** [comment]
@jxns Please see 
https://makecode.com/playground#basic-groups
https://makecode.com/defining-blocks

**Comment by abchatra** [comment]
>> Is this mandatory for an approval?

No, this is just a suggestion. It is up to you. @martinwork has shared the snippets. Thanks! 
Let me know how you want to proceed.

**Comment by jxns** [comment]
For now we would like to keep it this way. As the launch of our product is coming closer, we would like to release the extension first.

**Review by abchatra — APPROVED** [review]

**Review by abchatra — APPROVED** [review]

**Pull request merged**
