### PR TITLE
micro:coin activity

### PR DESCRIPTION
**Pull request by pelikhan**
Requires radio.sendBuffer support

### CODE REVIEW

**Comment by pelikhan** [comment]
LGTM

**Comment by pelikhan** [comment]
may need to have to change the reward system here

**Comment by ganicke** [comment]
Something more gratifying than just a number? Need to add a wallet.

**Comment by ganicke** [comment]
Send rewards to the "Duct tape wallet". Integrate it with  /projects/wallet

**Comment by ganicke** [comment]
After your reward fix I'll need to add note about how reward levels decay as complexity of the chain increases. I just know it.

**Comment by pelikhan** [comment]
Reward fix in.

**Pull request merged**
