### PR TITLE
Extensions: Add Joy Car

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @joy-it

### CODE REVIEW

**Comment by abchatra** [comment]
>> Copyright (c) Microsoft Corporation
Please change this to correct in the license.  This is not Microsoft package.

Looks good otherwise.

**Comment by abchatra** [comment]
@joy-it

**Comment by joy-it** [comment]
@abchatra thank you for your review! We fixed the license to the correct one.

**Comment by joy-it** [comment]
@abchatra  @microbit-mark I think `"url":"/pkg/DFRobot/joy-it/Joy-Car"` in the extensions.md is not correct, isn't it?
This also more of a robotics kit, is it possible to change the category?

**Comment by microbit-mark** [comment]
@joy-it It is in the Robotics category already. Hope that's okay.

**Comment by joy-it** [comment]
@microbit-mark thats perfect, thank you! But is the URL correct? Shouldn't this be just `"url":"/pkg/joy-it/Joy-Car",` instead of `"url":"/pkg/DFRobot/joy-it/Joy-Car",`?

**Pull request merged**
