### PR TITLE
include ws2812 ASM to avoid replication in packages

### PR DESCRIPTION
**Pull request by pelikhan**
Adds the necessary ASM to drive a strip of neopixels. Allows 3rd party to wrap it up in their products.
@mmoskal should/could we disable interrupts when we know that BLE is active?

### CODE REVIEW

**Comment by pelikhan** [comment]
@finneyj @jaustin

**Comment by jaustin** [comment]
@finneyj do we think this has any new feature interactions we need to be worried about?

**Comment by jaustin** [comment]
...Although it's a bit more work, one advantage of bringing this into C/C++ would be that we could use sd_nvic_critical_region_enter() / _exit() if we're running on top of SD instead of the CPSID/E - I don't *think* we have the tools do to that from TS?

**Comment by mmoskal** [comment]
@jaustin did you test `sd_nvic_critical_region_enter()`? Does it disable all interrupts? If we get any interrupt, the colors are completely out of sync.

**Comment by jaustin** [comment]
@mmoskal no, not tested - but I think it guarantees that the colours get out of sync rather than the radio. Users who have combined BLE with neopixel report colours stuttering, but not getting way out, just distortion or flicker. Peli said you'd seen hard crashes, though?

**Comment by pelikhan** [comment]
I could move this into the radio package. The goal here is to mitigate the proliferation of ws2812 drivers.

**Comment by abchatra** [comment]
I am not sure how ws2812 API belongs to radio (other than both can't work with ble). I also can't think of a better solution  😞.

**Comment by pelikhan** [comment]
It prevents it from Interrferrig with BLE, allows vendors to use and avoids adding a new package in the “add package” dialog.

________________________________

**Comment by pelikhan** [comment]
We're going to move this code into a github repo

**Comment by pelikhan** [comment]
ASM moved to https://github.com/microsoft/pxt-ws2812

**Pull request closed without merging**
