### PR TITLE
Adding missed dfrobot

### PR DESCRIPTION
**Pull request by abchatra**
Please double check everything: https://github.com/Microsoft/pxt-microbit/pull/970

### CODE REVIEW

**Comment by pelikhan** [comment]
Roll it back.
- [ ] no icon on package
- [ ] no release

**Comment by abchatra** [comment]
Oh was it intentional? Why is it in v0 ?

**Comment by pelikhan** [comment]
I expected Mark to check these things. We need to file bugs against that repo to get them to produce a release and get an icon.

**Comment by abchatra** [comment]
I am not reverting this now. Here is the scenario: On Friday 26th user can use dfrobot package but Monday due to update he can't

Lets keep it sync and if we want to roll back we need to do for both v0 & v1.

**Comment by pelikhan** [comment]
If it was already in v0, it's legacy now.

**Pull request merged**
