### PR TITLE
Port of Programmable Logic lesson for Logic Lab course

### PR DESCRIPTION
**Pull request by ganicke**
This is a port of the Programmable Logic lesson currently in PR - https://github.com/microsoft/pxt-adafruit/pull/1074.

### CODE REVIEW

**Comment by ganicke** [comment]
Build won't start.

```
The command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during .
```

**Comment by jwunderl** [comment]
I think that's the same thing as https://github.com/microsoft/pxt-blockly/pull/242, really really weird it's just showing up now..

**Comment by ganicke** [comment]
You had to tweak the ``travis.yml``?

**Comment by jwunderl** [comment]
Yah, they changed the defaults. Im playing around with it for a sec, have a branch to fix it just waiting for the build to pass~

**Comment by jwunderl** [comment]
should work after you merge in master again now~

**Comment by ganicke** [comment]
Cool, thanks.

**Pull request merged**
