### PR TITLE
I2C ref doc 'repeated' description

### PR DESCRIPTION
**Pull request by ganicke**
Try to clarify what the **repeated** parameter does, re: #1314.

Question: When **repeated** is `true`, will this NOT send the stop condition during the operation of the individual API call (when numbers or buffers are formed from multi-byte reads/writes but send the stop on the last byte read/write)? Or, will it NOT send the stop condition per API call at all (stop condition is not used at any time during byte transfers in the call)?

The use of **repeated** is not well described in any of the codal/mbed stuff:

https://github.com/lancaster-university/microbit-dal/blob/master/source/drivers/MicroBitI2C.cpp
https://lancaster-university.github.io/microbit-docs/ubit/i2c/
https://os.mbed.com/docs/v5.10/mbed-os-api-doxy/classmbed_1_1_i2_c.html

### CODE REVIEW

**Comment by ganicke** [comment]
Also, does `UInt8BE` an `Int8BE` really mean anything? Such a thing might indicate an MSB and LSB reversal of bit order in the byte, but really?

**Comment by pelikhan** [comment]
Big Endian or Little Endian

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mmoskal** [comment]
The BE and  LE don't mean anything in one byte case - they are there for consistency, though I guess that can be argued. The UInt and Int are differnt.

**Comment by pelikhan** [comment]
They are staying for legacy.

**Comment by pelikhan** [comment]
@ganicke see answer above.

**Comment by ganicke** [comment]
Thanks all for the info. It looks like the actual answer is down in here:

https://github.com/ARMmbed/mbed-os/blob/master/targets/TARGET_NORDIC/TARGET_MCU_NRF51822/i2c_api.c

where the stop is written once after all the byte writes/reads.

**Comment by ganicke** [comment]
RTM

**Pull request merged**
