### PR TITLE
Extension: add pxt-meter

### PR DESCRIPTION
**Pull request by martinwork**
Arising from https://support.microbit.org/helpdesk/tickets/68252 (private)
@GrandpaBond
@abchatra
https://github.com/GrandpaBond/pxt-meter
https://makecode.microbit.org/_VEK03yWCeYWo
image

### CODE REVIEW

**Comment by abchatra** [comment]
@GrandpaBond awesome cool extension.

Few minor comments
- One of the api uses capital case for the text to begin with (_Use digital meter_) in the blocks text and rest uses small cases. Better to be consistent?
- Can digital meter and other meters can be combined to do just one api? Something like following:
meter.use(meter.Styles._Digital_, 0, 100) //Instead of separate _meter.digital()_ api

**Comment by GrandpaBond** [comment]
The digital meter has a fixed range that cannot be scaled. Combining it with the analogue meters (which take a range definition) would suggest to the user that it can be.

**Comment by martinwork** [comment]
@abchatra @GrandpaBond We had already spotted the uppercase U. It didn't seem worth delaying creation of the PR to wait for that quick easy fix.

**Review by abchatra — APPROVED** [review]

**Comment by GrandpaBond** [comment]
Hi AbhijithI am delighted that my pxt-meter extension is now deployed. Currently the icon.png poster is not being displayed. Is there anything more I need to do to make this happen? Cheers    Nigel Bond (aka GrandpaBond) 
-------- Original message --------From: Abhijith Chatra ***@***.***> Date: 08/11/2023  17:15  (GMT+00:00) To: microsoft/pxt-microbit ***@***.***> Cc: GrandpaBond ***@***.***>, Mention ***@***.***> Subject: Re: [microsoft/pxt-microbit] Extension: add pxt-meter (PR #5392) 
Merged #5392 into master.

**Comment by martinwork** [comment]
@GrandpaBond Maybe a caching problem?

In the Extensions dialogue, I see

image

and at https://makecode.microbit.org/extensions#utilities

image

**Comment by abchatra** [comment]
I see as well: 

image

**Comment by GrandpaBond** [comment]
Hi AbhijithSorry, it was just a cacheing issue. All good now!Cheers     ---Nigel Bond
-------- Original message --------From: Abhijith Chatra ***@***.***> Date: 10/11/2023  18:14  (GMT+00:00) To: microsoft/pxt-microbit ***@***.***> Cc: GrandpaBond ***@***.***>, Mention ***@***.***> Subject: Re: [microsoft/pxt-microbit] Extension: add pxt-meter (PR #5392) 
I see as well:

**Pull request merged**
