### PR TITLE
Extensions: add BEP

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @Bouw-je-BEP

### CODE REVIEW

**Comment by abchatra** [comment]
@Bouw-je-BEP. Looks great overall.

One comment:

Language text is not rightly translated for the blocks. You need to have English text in the block definition and _locales/**/ file for any additional language. Otherwise it will be confusing for the users.  You don't need to have all languages under locales/** just the languages you care. 

Read more about how to rightly translate:
https://makecode.com/extensions/localization

**Comment by Bouw-je-BEP** [comment]
@abchatra thank you for the feedback and information!

Our accessory is only available in the Netherlands at the moment that's why the block definitions are in dutch. I'll take a look into translating via _locales// 

Is it possible for the extension to be added so our dutch users can already benefit from it?

**Comment by abchatra** [comment]
Thanks @Bouw-je-BEP 
Our filtering service might remove the blocks if they are of not the right format. So better to adhere to the semantics.

**Comment by Bouw-je-BEP** [comment]
Hey @abchatra 

I updated te repo and changed all the dutch to english. I will make a translation in the coming weeks to be added.

Thanks!

**Review by abchatra — APPROVED** [review]

**Comment by abchatra** [comment]
Thanks I will merge this. 

It is straight forward to add dutch. You need _locales/nl/ json file for strings.

**Pull request merged**
