### PR TITLE
Add spy versions of tutorials

### PR DESCRIPTION
**Pull request by pelikhan**
Creating a "text" version of the tutorial. Not changing the existing tutorials for legacy.

### CODE REVIEW

**Comment by ganicke** [comment]
`checkdocs` in the build is choking on its snippet collect I think.

**Comment by pelikhan** [comment]
Right, i've fix some paths, should be good now.

**Comment by ganicke** [comment]
Doh, I could've checked those.

**Comment by ganicke** [comment]
Wanna replace `() =>` to `function()` in those?

**Pull request merged**
