### PR TITLE
allow analog operations on digital pins

### PR DESCRIPTION
**Pull request by pelikhan**
Fix for https://github.com/Microsoft/pxt/issues/611

### CODE REVIEW

**Comment by pelikhan** [comment]
In v0.9.1

**Comment by nevilh** [comment]
Hi Peli et al,

You might be interested to know I have submitted a related idea to make Display GPIO available as Inputs **without** turning off the display. You can find details on the DAL GitHub page:

https://github.com/lancaster-university/microbit-dal/

It is issue [#266] and Joe has given an initial response on its feasibility.

Cheers,

Nevil

**Comment by OwenBrotherwood** [comment]
https://github.com/lancaster-university/microbit-dal/issues/266

**Comment by luniki** [comment]
I am experimenting with the Kitronik motor driver board (thanks for pelikhan/pxt-kitronik ).

To control the speed of the two motors one has to use PWM on pins P0 & P16 and P8 & P12. Currently I can only "analog write pin X to Y" to P0 (on https://pxt.microbit.org/ )

I downloaded this repo and installed everything. Everything seems to work AFAIK.

In my locally installed pxt I can now choose to "analog write pin X to Y" for the other pins P8, 12 and 16.

But after uploading it to the microbit it does nothing. The motor is not moving at all:

    input.onButtonPressed(Button.A, () => {
        pins.analogWritePin(AnalogPin.P8, 200)
        pins.digitalWritePin(DigitalPin.P12, 0)
    })

Of course using motor1 and PWMing P0 works:


    input.onButtonPressed(Button.B, () => {
        pins.analogWritePin(AnalogPin.P0, 200)
        pins.digitalWritePin(DigitalPin.P16, 0)
    })

Any ideas why this is not working?

**Comment by luniki** [comment]
Ah, I see this is related to https://github.com/Microsoft/pxt/issues/611

Correct?

**Comment by pelikhan** [comment]
Looks like so

**Pull request merged**
