### PR TITLE
Extensions: add maqueen plus

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @tangjie133

### CODE REVIEW

**Comment by tangjie133** [comment]
@abchatra Hi,abchatra，How long can it be approved？

**Comment by abchatra** [comment]
Sorry for the delay. Here are the comments:

- License says: "_Copyright (c) 2018 Sam El-Husseini"_.This should be changed to right copyright.
- This block seems typo:
image
- Category color looks incorrect
image


Optional feedback
Some of the blogs don't have student friendly names.
- what does CW mean in the following block:
image
- What does T & E mean below
image
You should look at the blocks and see how to make them student friendly.

Looks good otherwise.

**Comment by tangjie133** [comment]
Thank you for your advice，The third recommendation cannot be modified because it is generated automatically by the compiler，The second suggestion is not very clear. Please correct me，Thank you very much..

**Comment by abchatra** [comment]
>> The second suggestion is not very clear. Please correct me

What does _(stop:0 forward: 1 back:2)_ mean in that block? Dropdown doesn't have these values.

**Comment by abchatra** [comment]
Is the return value?

**Comment by tangjie133** [comment]
yes

**Pull request merged**
