### PR TITLE
Turn on diffs for 'spy' tutorials

### LINKED ISSUE #3264: Missing code highlighting in SPY tutorials
We're missing the line highlighting in the Spy tutorials.

image

### PR DESCRIPTION
**Pull request by ganicke**
Turn on diffs for the 'spy' tutorials. Individual highlights are removed due to enabling of diffs.

Closes #3264 

**Comment**: This will now highlight the entire block of code in a later step when new code is shown that is separate from the rest of the project. Is that acceptable/desired too?

image

### CODE REVIEW

**Comment by pelikhan** [comment]
The highlight all seems like a bug. It should turn off when the entire snippet is new.

________________________________

**Comment by pelikhan** [comment]
Use @resetDiff on those steps.

**Comment by pelikhan** [comment]
Use @resetDiff on those steps.

**Comment by ganicke** [comment]
OK, I'll try that.

**Comment by pelikhan** [comment]
@ganicke what's the status on this?

**Comment by ganicke** [comment]
I think this is RTM.

**Comment by ganicke** [comment]
@pelikhan do we still want this?

**Comment by pelikhan** [comment]
Nope

________________________________

**Comment by ganicke** [comment]
No diffs today.

**Pull request closed without merging**
