### PR TITLE
Move neopixel sendBuffer primitive into core

### PR DESCRIPTION
**Pull request by mmoskal**
Tested as this:

```typescript
//% shim=light::sendNeopixelBuffer
function send(pin: DigitalPin, buf: Buffer): void {}
```

### CODE REVIEW

**Comment by pelikhan** [comment]
chat about this?

**Comment by pelikhan** [comment]
let's do an upgrade rule that updates the shim

**Comment by pelikhan** [comment]
Rename to Neopixel to ws2812b

**Comment by mmoskal** [comment]
requires https://github.com/microsoft/pxt/pull/7044

**Pull request merged**
