### PR TITLE
Extension: add GatorUV

### PR DESCRIPTION
**Pull request by martinwork**

### CODE REVIEW

**Comment by martinwork** [comment]
@abchatra I can't see what is causing the CI build failure.

**Comment by abchatra** [comment]
I fixed the case issue. Can you add the author of this extension to this thread as well? 

Couple of minor comments 

1. I see only 3 blocks in the extension. I am not sure the intent of adding "more" to category. Can you just add to the default one.
image

2. Size of the png should be less than 100kb to help faster download. It is borderline. Can this be reduced?

**Comment by martinwork** [comment]
Thanks @abchatra . I stopped scrolling at the 3 red Error lines further up.

@loricrotser

**Comment by loricrotser** [comment]
This has been fixed. New tag is v1.1.3

**Review by abchatra — APPROVED** [review]

**Pull request merged**
