### PR TITLE
support flag argument

### PR DESCRIPTION
**Pull request by pelikhan**
Fix for https://github.com/microsoft/pxt-microbit/issues/1762

### CODE REVIEW

**Comment by pelikhan** [comment]
IMMEDIATE is not compatible with our runtime (at least currently). Leads to 914 error (PANIC_CALLED_FROM_ISR)

**Comment by abchatra** [comment]
Lets take this. Block works with new default argument and backward compatible right?

**Comment by pelikhan** [comment]
Tested on hardware.

**Comment by pelikhan** [comment]
Yes old blocks load without issues.

**Pull request merged**
