### PR TITLE
Changing the default group to zero

### PR DESCRIPTION
**Pull request by abchatra**
Fixes https://github.com/Microsoft/pxt-microbit/issues/2017

### CODE REVIEW

**Comment by mmoskal** [comment]
I don't have a strong opinion, but it is a breaking change.

**Comment by abchatra** [comment]
Yes it is, but no one understood the old behavior. So hoping no one would have taken dependency.

**Comment by pelikhan** [comment]
The current behavior is designed to avoid clashes in a classroom. This is a breaking change.

**Comment by abchatra** [comment]
I understand. It is not working as no one knows a special magical hash is generated. Even mark from foundation didn't know about it.

**Comment by pelikhan** [comment]
Yes it just works. If we make this change, we will have more collisions in a classroom setting so we need to bump up the position of "set group" and document thoroughsly -- otherwise radio programs will trigger randomly once you have a classroom of device streaming packets.

**Comment by pelikhan** [comment]
@finneyj

**Comment by abchatra** [comment]
Sorry I disagree. Currently everyone assumes they have to setGroup to communicate with others. They don't understand that if they flash the same program across multiple microbits it would magically work for those microbits. 

It is a clever trick. Reality is broadcasting on group zero is better. Python does the same.

**Comment by pelikhan** [comment]
This change needs to be documented and "set group" should be moved up in the first set of "sender blocks".

**Comment by jaustin** [comment]
Can we do some specific in-classroom testing of both behaviours before putting this change live please? I've seen real confusion over collisions happening with the Python Editor where the default 'declash' isn't there. Totally agree this needs work, though, as the 'magic radio group' is clever but also invisible... In some ways it just punts the problem down the line or makes it seem like 'radio' isn't working.

The biggest issue with a broadcast group is that people are often building their own communications protocol (for example, '1' means 'heart', '2' means dog) and if you get input you're not expecting it's really hard to separate logic errors from miscellaneous radio activity. I've seen a classroom where people send around the string "STOP USING RADIO".

I wonder though, if *just* moving the 'radio set group' up might do the trick? If you make that more visible it'll help people get to it when they need to be in the same group.

@microbit-giles and @finneyj might be able to help work out how/where to test.

**Comment by pelikhan** [comment]
I am in favor of putting “set group” as the first block in the radio category —and— add “set group” as a first step in all tutorials/projects.

Choosing the channel is logically the first thing you do when you use any kind of talkie-walker. We are no different here.

**Pull request closed without merging**
