### PR TITLE
Intro to CS curriculum intro and first lesson

### PR DESCRIPTION
**Pull request by ganicke**

### CODE REVIEW

**Comment by pelikhan** [comment]
LGTM.

**Comment by ganicke** [comment]
OK

**Comment by pelikhan** [comment]
Make sure the image size are reasonable as well.

**Comment by ganicke** [comment]
I've restricted them to <= 674px in width to reduce file size and fit in "ui text". We can tune the sizes. Maybe Sam knows what the best size should be.

**Comment by pelikhan** [comment]
800 wide is fine too. Just no 4mb files.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
