### PR TITLE
Updating hero banner

### PR DESCRIPTION
**Pull request by samelhusseini**
hero

### CODE REVIEW

**Comment by Jaqster** [comment]
Can you move the blocks to be more centered (move to the right a bit)?  Also, did you see what the other colored background looked like?

**Comment by samelhusseini** [comment]
- [ ] Center the blocks
- [ ] Connect the red pin to the micro:bit

**Comment by samelhusseini** [comment]
How's the latest version @Jaqster?

**Comment by Jaqster** [comment]
Did you move the blocks over to the right?  I can't tell...  Maybe if you could leave the servo motor on the left, and move the micro:bit guy with the blocks so it's in the center, that would help spread the elements out a bit more.

**Comment by samelhusseini** [comment]
Okay how about this?

hero1

**Comment by Jaqster** [comment]
Perfect!  Ship it!

**Comment by samelhusseini** [comment]
Awesome!

**Pull request merged**
