### PR TITLE
add emakefun motorboat

### PR DESCRIPTION
**Pull request by emakefun**

### CODE REVIEW

**Comment by emakefun** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by emakefun** [comment]
@microsoft-github-policy-service agree company="Emakefun"

**Comment by martinwork** [comment]
@emakefun Please see
https://support.microbit.org/en/support/solutions/articles/19000054952-makecode-extension-and-tutorial-approval

**Comment by abchatra** [comment]
@emakefun can you please follow the process documented. I will close the PR for now and let Martin open the PR,

**Pull request closed without merging**
