### PR TITLE
add RVR

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @meganrobinson22

### CODE REVIEW

**Comment by abchatra** [comment]
This is blocking on this bug: https://github.com/sphero-inc/sphero-sdk-microbit-makecode/issues/2 
I can't test the package.

**Comment by meganrobinson22** [comment]
Hey @abchatra, in case you didn't see the updates on that issue you linked, the license problem should be fixed now. Let me know if there's anything else that needs to be changed!

**Comment by pelikhan** [comment]
You need to create a release. The easiest is to import your repository in https://makecode.microbit.org/beta and use "Create Release" in the git view.

**Comment by meganrobinson22** [comment]
Thanks @pelikhan, I just created a release. Is there anything else I need to do?

**Comment by pelikhan** [comment]
Looks good now. Waiting for the build.

**Pull request merged**
