### PR TITLE
Extensions: Add Cytron edubit

### PR DESCRIPTION
**Pull request by microbit-mark**
@abchatra Do not merge until product listing is live https://www.cytron.io/p-edu-bit

cc @waiweng83 can you let us know on this Pull Request when the product listing is live on your website?

### CODE REVIEW

**Comment by abchatra** [comment]
@waiweng83 well designed simple set of blocks. I love it. 

Couple of comments: 
1. Can you just point to pxt-neopixel as the dependency instead of exact version? 
"NeoPixel": "github:microsoft/pxt-neopixel"
Is there a need for the exact version? 
2. Remove installedVersion from the pxt.json

>> do not merge until product listing is live https://www.cytron.io/p-edu-bit

Sure, but merging won't do anything other than surface it when someone searches for the extension with the name. As long as it is not advertised anywhere it is a no-op.

**Comment by waiweng83** [comment]
> Can you just point to pxt-neopixel as the dependency instead of exact version?
> "NeoPixel": "github:microsoft/pxt-neopixel"
> Is there a need for the exact version?

We point it to exact version just to prevent future update of pxt-neopixel breaking our extension.
What's the better way of doing that?

**Comment by abchatra** [comment]
>> We point it to exact version just to prevent future update of pxt-neopixel breaking our extension.
Is there a better way of doing that?

Up to you.  If there are bug fixes in neopixel library you won't receive them either.  We try to maintain backward compat. So unlikely future update will break your extension.

**Comment by waiweng83** [comment]
> > > We point it to exact version just to prevent future update of pxt-neopixel breaking our extension.
> > > Is there a better way of doing that?
> 
> Up to you. If there are bug fixes in neopixel library you won't receive them either. We try to maintain backward compat. So unlikely future update will break your extension.

In that case, we prefer to point it to exact version. If there is future update on the neopixel extension, we will test it out and update the version manually.

**Comment by abchatra** [comment]
Ok sounds good @pelikhan fyi

**Comment by waiweng83** [comment]
Did I left out anything else to get it merged?

**Comment by abchatra** [comment]
It is ready to be merged. Waiting for you to give green signal

**Comment by waiweng83** [comment]
I hope that it can be merged now instead of waiting for the product to be launched.
So that we can prepare the handbook with actual user experience.

Thanks.

**Pull request merged**
