### PR TITLE
Support latest PXT with GC

### PR DESCRIPTION
**Pull request by mmoskal**
Requires https://github.com/Microsoft/pxt-common-packages/pull/661

Now builds and simple hello world works. nothing else tested

- [x] blinky
```
basic.forever(function () {
    basic.showLeds(`
        . . . . .
        . . . . .
        . . # . .
        . . . . .
        . . . . .
        `)
    basic.showLeds(`
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        `)
})
```
- [x] icons panic 984
```
basic.forever(function () {
    basic.showIcon(IconNames.Heart)
    basic.showLeds(`
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        `)
})
```
- [x] string alloc
```
basic.forever(function () {
    let s = Math.random().toString()
    basic.showString(s)
})
```

### CODE REVIEW

**Comment by riknoll** [comment]
What's the status of this PR?

**Comment by pelikhan** [comment]
Still some panic on HW.

**Comment by mmoskal** [comment]
Fixed flashing heart (with pxt PR)

**Comment by abchatra** [comment]
@mmoskal Is this ready to be merged? Looks good to me.

**Comment by mmoskal** [comment]
Should be good. I'm not sure why the build is failing

**Comment by riknoll** [comment]
Build is fixed. Good to merge?

**Comment by mmoskal** [comment]
Good for me ;)

**Comment by mmoskal** [comment]
🎊

**Pull request merged**
