### PR TITLE
Music reorg

### PR DESCRIPTION
**Pull request by pelikhan**
Fix for https://github.com/microsoft/pxt-microbit/issues/2971 . Same as suggested aside from:

- moving new melody block on top
- moving old melody blocks to bottom

image

### CODE REVIEW

**Comment by pelikhan** [comment]
Fix for https://github.com/microsoft/pxt-microbit/issues/2971

**Comment by Jaqster** [comment]
Are we trying to deprecate the old melody blocks?  If we are, fine.  But if not, the new Play Melody block is not really a substitute...

**Comment by abchatra** [comment]
One suggestion. Instead of _Melody Advanced_, make sub title just _More_. We can lump un-important blocks there.

**Comment by abchatra** [comment]
_Are we trying to deprecate the old melody blocks? If we are, fine. But if not, the new Play Melody block is not really a substitute..._

Once we introduce play melody, very few users will use start melody blocks.

**Comment by pelikhan** [comment]
Yes we are trying to align melody system across all boards. The new block is more creative.

________________________________

**Pull request merged**
