### PR TITLE
Disabling extensions in the v2 which are not building

### PR DESCRIPTION
**Pull request by abchatra**
List from #3506

### CODE REVIEW

**Review by mmoskal — APPROVED** [review]

**Review by pelikhan — APPROVED** [review]

**Comment by abchatra** [comment]
I tested using pxt-bluetooth-temperature-sensor extension. Compilation succeeds and I can flash v1 hardware. If I flash v2 hardware with the same hex file it fails with 506 error. I believe this is expected.

**Comment by abchatra** [comment]
I will merge the change tomorrow. @jaustin for visibility.

**Comment by mmoskal** [comment]
I think it should be panic 927

**Comment by jaustin** [comment]
Yes, 506 is from the DAPLink range, so suggests something else.

**Comment by jaustin** [comment]
@abchatra can you share the hex file please? Or is there an editor instance that does this?

**Comment by abchatra** [comment]
It gave me E927 on second try. I am not sure what is wrong with my v2. Probably before I haven't updated bootloader to 0255 yet. @jaustin can you send me instruction?

**Comment by jaustin** [comment]
Yea, can send instructions, but for now can you share a hex so we can do a full test across other platforms in case there's something related to the hex. 

506 can be caused if there's still webUSB activity going on when drag-and-drop starts

**Comment by 4tronix** [comment]
Panic 927 is described here as "You are trying to use a feature designed for micro:bit V2 on a V1 board." This is clearly going to confuse users. https://support.microbit.org/support/solutions/articles/19000016969-micro-bit-error-codes
I released the fix for BitCommander but then started getting this 927 error without any explanation :(

**Comment by mmoskal** [comment]
@abchatra The 4tronix line needs to be updated to:

```
            "4tronix/bitcommander": "min:1.1.1",
```

note that it's `1.1.1` not `v1.1.1`, because that's how the tag in repo is called. Should the tag be `v2.3.4` then it would be `min:v2.3.4`.

@4tronix you can submit a PR if you want.

@jaustin the error description should be extended with something like 'or the extension you're using is only compatible with v1'; the actual error is `variant not supported`.

**Comment by microbit-mark** [comment]
Thanks @4tronix @mmoskal I have updated the error description accordingly.

**Pull request merged**
