### PR TITLE
micro:bit v2 compatibility: Update Tinkertanker extension versions

### PR DESCRIPTION
**Pull request by Mireille-T**
Update tinkertanker/pxt-rotary-encoder-ky040 to v1.2.1 as this release should now be compatible with the micro:bit v2.

### CODE REVIEW

**Comment by Mireille-T** [comment]
Full list of updates for release version compatibility with the micro:bit v2:
- [tinkertanker/pxt-range-vl53l0x](https://github.com/tinkertanker/pxt-range-vl53l0x) - `v1.0.1`
- [tinkertanker/pxt-alphanumeric-ht16k33](https://github.com/tinkertanker/pxt-alphanumeric-ht16k33) - `v1.1.0`
- [tinkertanker/microDriver_SHT2x](https://github.com/tinkertanker/microDriver_SHT2x) - `v1.0.0`
- [tinkertanker/pxt-rotary-encoder-ky040](https://github.com/tinkertanker/pxt-rotary-encoder-ky040) - `v1.2.1`

**Review by abchatra — APPROVED** [review]

**Comment by abchatra** [comment]
@Mireille-T Thanks and it looks good. 

Can you please signoff license?

**Comment by Mireille-T** [comment]
Apologies but I think I had already signed off the license before I added the later commits but the status has not been updated, is there any way to resolve this issue? Thank you!
image

**Comment by abchatra** [comment]
Thanks for confirming.

**Pull request merged**
