### PR TITLE
Extensions: add longanbit

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @lionyhw

### CODE REVIEW

**Comment by lionyhw** [comment]
@abchatra Please check the pull request.

**Comment by abchatra** [comment]
Sorry I missed this. 

Question:
This package is dependent on non-whitelisted packages: 
        "SSD1306_OLED": "github:longan-link/pxt-oled",
        "neopixel": "github:elecfreaks/pxt-neopixel"

Why not use approved Microsoft/pxt-neopixel package? 
Also you need to whitelist longan-link/pxt-oled.

**Comment by lionyhw** [comment]
> Sorry I missed this.
> 
> Question:
> This package is dependent on non-whitelisted packages:
> "SSD1306_OLED": "github:longan-link/pxt-oled",
> "neopixel": "github:elecfreaks/pxt-neopixel"
> 
> Why not use approved Microsoft/pxt-neopixel package?
> Also you need to whitelist longan-link/pxt-oled.

There is no Chinese translation for both packages in the white list.
Can we add the file of "longan-link/pxt-OLED" to the "pxt-longmbit" package to make it a package to join the white list?
@abchatra

**Comment by lionyhw** [comment]
> You can give PR request to add localization to those repos. Can you please do that?
> Otherwise bugs fixes in one package won't be propagated.

Neopixel is not merged
https://github.com/microsoft/pxt-neopixel/pull/50#issue-380328643

OLED doesn't display Chinese, I can't find the problem
https://github.com/Tinkertanker/pxt-oled-ssd1306/blob/49f1fc34cf855652f21dfd9a5468e8af533c1b8a/pxt.json#L12
@abchatra

**Comment by abchatra** [comment]
For Microsoft\neopixel you haven't fixed the code review comment. Please fix it.

**Comment by abchatra** [comment]
I will merge after that.

**Comment by abchatra** [comment]
_OLED doesn't display Chinese, I can't find the problem_

Can you elaborate this issue? I don't understand. How did you fix this in your fork?

**Comment by lionyhw** [comment]
> _OLED doesn't display Chinese, I can't find the problem_
> 
> Can you elaborate this issue? I don't understand. How did you fix this in your fork?


I fixed the problem

OLED link to"Tinkertanker/pxt-oled-ssd1306"

**Comment by lionyhw** [comment]
Done @abchatra

**Comment by lionyhw** [comment]
Can you merge this PR as soon as possible so that my users can search more easily.
Although the neopixel package lacks a Chinese translation, it looks like it will be finished soon.
Or what else needs to be done?
@abchatra

**Comment by abchatra** [comment]
Thanks for addressing the comments. I have also merged the pxt-neopixel merge request.

**Pull request merged**
