### PR TITLE
CSIntro educator material page

### PR DESCRIPTION
**Pull request by ganicke**
A proposed page and layout for providing the CSIntro educator materials.

As a way to not clutter up the current csintro course, we could offer the educator materials as a separate edition of csintro. It seems that the course is now kind of provided as a “product” so I pulled it into a course category of its own.

image

Then, on the current course page, a link to the educator edition is added:

image

The new educator materials are provided on another course page which simply has links to all the materials:

image

Links to be added when CDN and video uploads are complete.

### CODE REVIEW

**Comment by pelikhan** [comment]
How do we prevent them from diverging?

**Comment by ganicke** [comment]
@pelikhan they already have diverged. The content format and organization between the original markdown and this new DOC/PDF stuff isn't 100% one-to-one.

**Comment by pelikhan** [comment]
How much divergence? Can we backport fixes to the existing markdown sources?

**Comment by ganicke** [comment]
Within the actual sections that map back to the original course, yes. Look for example at the new stuff in the variables lesson, **Unplugged activity: Keeping score** section:

https://onedrive.live.com/view.aspx?cid=cd2e5904969cf22d&page=view&resid=CD2E5904969CF22D!256&parId=CD2E5904969CF22D!238&authkey=!AI5-TNis0k4nZFo&app=Word

...and then in the **Unplugged** page in the original course:

https://makecode.microbit.org/courses/csintro/variables/unplugged

The actual core content is the same but only for that one subsection in the lesson material doc.

**Comment by ganicke** [comment]
There's no MakeCode branding on the logo images. Add some?

**Comment by Jaqster** [comment]
Yes, please :-)

**Comment by ganicke** [comment]
Educator material page is at: https://makecode.microbit.org/courses/csintro-educator

**Comment by ganicke** [comment]
@Jaqster - blog it? Got something for https://educationblog.microsoft.com or a badge on https://www.microbit.org/teach?

**Pull request merged**
