### PR TITLE
Show block for isGameOver(),isRunning(),isPaused()

### PR DESCRIPTION
**Pull request by xuefengedu**
Current gameOver function will showScore, when the user add the score after gameover(e.g. press A button to add the score), the score will changing always, to avoid this kind of issue for block kids/users, I add this three block to show, thanks.

showScore() issue in gameOver:
https://github.com/Microsoft/pxt-microbit/blob/08e9c9c4166c271e15ef802a4628cfe326fca62d/libs/core/game.ts#L140

### CODE REVIEW

**Comment by xuefengedu** [comment]
@pelikhan  sure, do you mean screenshot for new 3 blocks or screenshot for the issue?

**Comment by pelikhan** [comment]
The new blocks...

**Comment by xuefengedu** [comment]
@pelikhan got it, will do it,thanks.

**Comment by xuefengedu** [comment]
@pelikhan screenshot as below, thanks.
mb_pr2
mb-pr

**Comment by xuefengedu** [comment]
@pelikhan could you help to merge this PR? thanks very much!

**Pull request merged**
