### PR TITLE
Enable Clever for Microbit

### PR DESCRIPTION
**Pull request by benvillalobos**
## Changes
- Add Clever logo and metadata in pxtarget.json, enabling it for the target.

**NOTE:** Clever will only be enabled if query param `clever=1` is passed.

Should merge _after_ https://github.com/microsoft/pxt/pull/9458 and https://github.com/microsoft/pxt-backend/pull/804.

### CODE REVIEW

**Comment by eanders-ms** [comment]
Does Clever have a iconic brand logo? An icon would look better on the login button.

**Comment by benvillalobos** [comment]
Modified the PR to only enable when query param `clever=1`.

Without `clever=1`:
image

With `clever=1`:
image

**Comment by eanders-ms** [comment]
Ok. The inverted logo might pop better on the white button
image

Taken from https://clever.com/about/media-kit

**Comment by benvillalobos** [comment]
Unfortunately it's not an inverted color scheme there, they use the blue BG to emphasize the white text. It's really just an svg of white text.

Their guidelines suggest not recoloring it, in theory we could use modify it with their suggested blue as a background.

> While we’re constantly innovating, the Clever logo appreciates consistency. Please don’t edit or recolor the logo.

**Comment by eanders-ms** [comment]
Screenshot is directly from their branding guidelines, so probably fine to use if we want it.

**Comment by benvillalobos** [comment]
Using the logo taken straight from the image on the media kit site:

image

**Comment by benvillalobos** [comment]
Here was the before:

image

**Comment by benvillalobos** [comment]
We just got an official C icon from the Clever folks. Looks good!

image

**Comment by benvillalobos** [comment]
Note these are good to merge and the Clever folks will need these changes to test our arcade and micro:bit apps. When this is approved, please merge as well! The micro:bit app will forward to makecode.microbit.org/beta?clever=1&autologin=1

**Review by abchatra — APPROVED** [review]

**Pull request merged**
