### PR TITLE
added LINE beacon package

### PR DESCRIPTION
**Pull request by microbit-mark**
Developer has met Foundation requirements for adding this package. It will be moved out of BETA today.

### CODE REVIEW

**Comment by pelikhan** [comment]
Missing README description, missing icon.png. Did this package get reviewed?

**Comment by microbit-mark** [comment]
I've requested the changes from @hisayan

**Comment by hisayan** [comment]
I removed BETA from the description and added icon.png

**Comment by pelikhan** [comment]
Thanks. Please beef up the README:
image

**Comment by hisayan** [comment]
I had made README.md from the beginning.
https://github.com/pizayanz/pxt-linebeacon/blob/master/README.md
anything wrong ?

**Comment by pelikhan** [comment]
You need to include it in the “files” array in pxt.json 😊

**Comment by pelikhan** [comment]
You should also add a dependency on “Bluetooth” since you are relying on Bluetooth (this will prevent to mix your package with radio).

**Comment by hisayan** [comment]
Thanks
add README.md and bluetooth dependencies

**Pull request merged**
