### PR TITLE
added iBit package by Innovative Experiment

### PR DESCRIPTION
**Pull request by microbit-mark**
https://support.microbit.org/helpdesk/tickets/4766
Innovative Experiment have worked with the foundation to approve this package for the sloth bit product.

### CODE REVIEW

**Comment by pelikhan** [comment]
@microbit-mark can you resolve the conflicts?

**Comment by microbit-mark** [comment]
Have resolved conflicts @pelikhan

**Comment by pelikhan** [comment]
- block names should be camelized to stay consistent with other APIs

**Comment by pelikhan** [comment]
- delete https://github.com/emwta/pxt-iBit/blob/master/ibitboard.png

**Comment by pelikhan** [comment]
- release needs to be added using ``pxt bump``

**Comment by themarkness** [comment]
Thanks @pelikhan 

@emwta can you fix the issues raised?

**Comment by emwta** [comment]
me changed icon.png less than 300kb.

**Comment by pelikhan** [comment]
I have opened 4 issues on the package repo.

_____________________________

**Comment by emwta** [comment]
Delete ibitboard.png

Block name change does not match other API.

**Comment by pelikhan** [comment]
@microbit-mark make sure packages are also added to the summary so that they are crawlable

**Comment by microbit-mark** [comment]
can you eleborate @pelikhan what is the summary?

**Pull request merged**
