### PR TITLE
Extension: Add Kitronik Air Quality V2

### PR DESCRIPTION
**Pull request by microbit-mark**
This is a V2 specific version of the extension with added features.

I am not including this on https://makecode.microbit.org/extensions as one of the extensions is already listed. 

cc @AlasdairAtKitronik

### CODE REVIEW

**Review by abchatra — APPROVED** [review]

**Comment by abchatra** [comment]
@AlasdairAtKitronik Extension overall looks great.

Couple of questions:

1. Is there a reason for hard dependency on the versions here? It is better to not specfiy the versions if you wan to take the latest tagged versions of these dependent package. 

        "kitronik_RTC": "github:KitronikLtd/pxt-kitronik-rtc-base#v0.0.12",
        "kitronik_BME688": "github:KitronikLtd/pxt-kitronik-bme688-base#v0.0.7",
        "kitronik_EEPROM": "github:KitronikLtd/pxt-kitronik-eeprom-base#v0.0.2",
        "kitronik_OLED_V2": "github:KitronikLtd/pxt-kitronik-oled-base-V2-only#v0.0.5"

2. Can you reduce the size of icon.png to less than 100kb? Helps us in managing the bandwidth of the site.

3. Remove the main.blocks from the pxt.json if you don't need it.

**Comment by AlasdairAtKitronik** [comment]
@abchatra I'll try and make those changes as soon as possible - you're right, there's no need for the hard coded versions!

**Comment by AlasdairAtKitronik** [comment]
@abchatra All changes made and new release created - it's good to go live in my opinion.

**Review by abchatra — APPROVED** [review]

**Comment by abchatra** [comment]
Looks great to me.

**Pull request merged**
