### PR TITLE
Extension: Add Kid Spark Spark:bit

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @Aerospacesmith @halspeed

### CODE REVIEW

**Comment by abchatra** [comment]
Looks good. 

I am unsure if this category needs to be at the top. Basic category is needed if you are starting anything. Probably add after input? 
image

**Review by abchatra — APPROVED** [review]

**Review by abchatra — APPROVED** [review]

**Comment by halspeed** [comment]
Thank you for approving @abchatra. The vast majority of our users will enter the editor from our website instead of the typical "add extension" flow since micro:bit is embedded in the Kid Spark product (Spark:bit). So we thought it best to put our categories at the top.

How do we get Microsoft approval for our tutorials to remove the "report abuse" button? https://github.com/KidSpark/tutorials

**Comment by abchatra** [comment]
To use the boolean blocks you need if condition blocks. So ideally first used blocks need to be at the top. It is not about where the land from. It is about what program students are writing. I am not aware what content is being presented here. 

I am still formulating the approval process for tutorials.

**Comment by halspeed** [comment]
@abchatra the images and the render script for the README.md aren't working after the merge: https://makecode.microbit.org/pkg/KidSpark/pxt-sparkbit

**Pull request merged**
