### PR TITLE
Extensions: add DFRobot microIoT

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @tangjie133

### CODE REVIEW

**Comment by tangjie133** [comment]
What do i need to do？

**Comment by abchatra** [comment]
We will review the extension by EOD tomorrow

**Comment by abchatra** [comment]
@tangjie133 I looked at your extension. I have some feedback. I believe you can simplify your blocks for students. 

- initDisplay - Can this be done automatically, If this needs to be done every time, why expose the block and just do this in the constructor.
- UI
- IOT_ID and IOT_PWD, just call ID & Password. They more explicit.
- Remove unwanted information such as Iot-service or start connection.
- MQTT, use kid-friendly messages here? 

image

Overall look at all of your api and see if the student really needs them and how to make it simple. 
All the above are suggestions and it is your extension and you can choose what to display to the students.

**Comment by tangjie133** [comment]
There is no way to cancel the initialization of the OLED module. Other problems have been modified. Please check it once.

**Comment by abchatra** [comment]
@tangjie133  can you do the release of your extension? As you have made changes, it needs a release.

**Comment by tangjie133** [comment]
ok

**Comment by tangjie133** [comment]
How long can I find it from the official website ：）

**Pull request merged**
