### PR TITLE
add drive:bit

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @4tronix

### CODE REVIEW

**Comment by 4tronix** [comment]
Should I be able to search for DriveBit extension now? I can't find it?

**Comment by microbit-mark** [comment]
@abchatra any reason this is not showing up yet?
Screenshot 2019-10-25 at 15 21 21

**Comment by abchatra** [comment]
we will investigate. Not sure why it is not coming up in search. ktronix/drivebit seems to come up

**Comment by 4tronix** [comment]
but "ktronix" is not the same as "4tronix" ??

Best regards,
Gareth

------ Original Message ------

**Comment by microbit-mark** [comment]
I think it's actually 4tronix, see Screenshot 2019-10-28 at 08 33 42. Still it should show up under the general search for '4tronix' or 'drive:bit'

**Comment by abchatra** [comment]
Yes sorry, I meant 4tronix/drivebit

**Comment by 4tronix** [comment]
Yes, if you enter 4tronix/drivebit in the search box it finds it. But 
not if you enter 4tronix, nor if you enter drivebit. Can you fix it?

Best regards,
Gareth

------ Original Message ------

**Comment by abchatra** [comment]
Yes we will investigate.

**Comment by 4tronix** [comment]
What are the results of your investigation? It has been 2 weeks now and customers still can't easily access it?

**Comment by abchatra** [comment]
Sorry, bit busy week for us. ETA: 11/8

**Comment by abchatra** [comment]
We deployed a fix to the backend. There is some issue with caching and it is not reproducing in our local environment. Hopefully this address the issue. If not we will continue our investigation. 

Fix will go live in 4 hours. 

This bug is harder than we initially thought.

**Comment by abchatra** [comment]
Verified this is fixed

**Comment by 4tronix** [comment]
Great news. I can confirm it is fixed (and also other things that hadn’t rippled through)

**Pull request merged**
