### PR TITLE
Extensions: Add strawbees kit

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @paulobarcelos

### CODE REVIEW

**Comment by abchatra** [comment]
@paulobarcelos Well written extension. Kudos!

On request. There is a BSD license. Can you create a third-party-notices.txt file at the root of the repo and add the license for the easing function there? 
Similar to this: https://github.com/microsoft/pxt-microbit/blob/master/THIRD-PARTY-NOTICES.txt

**Comment by paulobarcelos** [comment]
@abchatra Thanks for the feedback! Added the file! https://github.com/strawbees/pxt-robotic-inventions/blob/master/THIRD-PARTY-NOTICES.txt

All good now?

**Comment by abchatra** [comment]
Thanks merged.

**Comment by paulobarcelos** [comment]
Thanks @abchatra!

Uppon inspection I've found and created two issues.

One regarding how the name of the extension is displayed (should be `Strawbees Robotic Inventions` but instead it is `robotic-inventions`) -> #2596

And another regarding how the code snipets are broken on the "read more" page -> #2595

**Pull request merged**
