### PR TITLE
Extension: Add Joy-IT RFID mfrc522

### PR DESCRIPTION
**Pull request by microbit-pauline**
Add Joy-IT RFID mfrc522 extension

### CODE REVIEW

**Review by jwunderl — COMMENTED** [review]
@microbit-pauline could you add the repo

**Comment by joy-it** [comment]
Any updates on this?
The linked PDF is the manual to our product. We will update this with the Micro:Bit part as soon as the extension is approved and publicly available.

**Comment by abchatra** [comment]
@microbit-carlos can you please do the first round of approval with updating target.config. If you are not the right person let me know.

**Comment by martinwork** [comment]
@abchatra, @carlosperate has given me access to sort this out.

**Comment by martinwork** [comment]
@abchatra @jwunderl @joy-it Done:
https://github.com/microsoft/pxt-microbit/pull/4809/commits/f2db9b0e6ff6e6717ad4842b1143b4cc57ff48b7

**Comment by martinwork** [comment]
@microbit-carlos I suspect this was added to preferredRepos by mistake. Should it be moved to approvedRepos?

**Comment by abchatra** [comment]
I have removed it from preferredrepo list. 

Going ahead it is sufficient to approvedRepoLib section. Ignore older sections, they are not used anymore.

**Review by abchatra — APPROVED** [review]

**Comment by martinwork** [comment]
> Going ahead it is sufficient to approvedRepoLib section. Ignore older sections, they are not used anymore.

Thanks @abchatra !

**Comment by joy-it** [comment]
I still cannot find the extension in the makecode extension browser. Is something missing here?

**Comment by abchatra** [comment]
I do see under "individual sensors"
image


What keyword are you searching?

**Comment by joy-it** [comment]
I tried "Joy-IT" (that where we usually find all our extensions) as well as "mfrc522" and "ads1115" but they dont appear with those keywords.

**Comment by abchatra** [comment]
I don't think so that is the issue. @joy-it can you add the keywords to the description of your repo?

**Comment by abchatra** [comment]
I think this is a bug in our backend. Let me take a look

**Comment by joy-it** [comment]
Where exactly should I add the keywords? I never used keywords in any extension before and never had a problem finding them.

**Comment by abchatra** [comment]
Sorry for my earlier keyword comment, this is not an issue on your end. Our backend has a bug which we are in the process for fixing.  You don't need to do anything, other than wait for the bug to be fixed.

**Comment by martinwork** [comment]
@abchatra Should I make a PR to change "Individual sensors" to "Science"?

**Comment by abchatra** [comment]
If it makes sense please do. That is not the issue here though. We have a bug in backend which is not allowing new extensions to be searchable.

**Pull request merged**
