### PR TITLE
Extension: add button-clicks

### PR DESCRIPTION
**Pull request by martinwork**
cc @bsiever

### CODE REVIEW

**Comment by abchatra** [comment]
Looks good overall. Nice extension.

Minor nit: @bsiever can you remove more category. It is just few blocks and more category is not recommended when you have less than 10 blocks. Put the more category blocks lower in the hierarchy. 
image

**Comment by abchatra** [comment]
@martinwork please add @ me to these extensions PR. I will miss it otherwise.

**Comment by martinwork** [comment]
Will do, thanks @abchatra

**Comment by bsiever** [comment]
@abchatra: I'm open to that, but I was a little afraid that the features I put in Advanced aren't really the core functionality and may add some confusion about which blocks to use.   But I agree that it's a little silly to have a separate toolbox spot just for two blocks.   Thoughts?

**Comment by bsiever** [comment]
@abchatra Ignore my previous post.  I removed the "More" category and used an "Advanced" group for those two blocks (forgot that was possible until I was doing something else).  Update has been committed.

**Review by abchatra — APPROVED** [review]

**Pull request merged**
