### PR TITLE
Bumping common packages for mic state changes

### PR DESCRIPTION
**Pull request by srietkerk**

### CODE REVIEW

**Comment by srietkerk** [comment]
The build is failing because the microphone state that is in the DalBoard object is saying the type is `AnalogSensorState`. This is changed to `MicrophoneState` here: https://github.com/microsoft/pxt-microbit/pull/5199.

This is a sort of chicken and the egg situation.. Is there a best way to approach common package dependencies like this? Is it best to merge the micro:bit changes and just have beta broken for a bit and then bump common packages?

**Comment by jwunderl** [comment]
just bump in the other pr, it doesn't need to be it's own pr

**Comment by thsparks** [comment]
Ack I pressed the wrong button sorry!

**Comment by thsparks** [comment]
Reopen

**Comment by thsparks** [comment]
But I do agree w/ Joey's point, probably best to include in [the new PR.](https://github.com/microsoft/pxt-microbit/pull/5199)

**Comment by srietkerk** [comment]
Ha, you were just doing my work for me, @thsparks!

Closing to bump in my current PR.

**Pull request closed without merging**
