### PR TITLE
add-sw01

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @luqmaanb @PragmaticPhil

### CODE REVIEW

**Comment by microbit-mark** [comment]
please follow up on this one @abchatra @pelikhan

**Comment by PragmaticPhil** [comment]
Thanks Mark :)
@pelikhan / @abchatra - please let me know if there is anything I can do to help this one progress.

**Comment by PragmaticPhil** [comment]
Issues have been addressed so please let us know if there is anything we can do to help this one progress.

**Comment by abchatra** [comment]
@PragmaticPhil Looks like the repo is missing license.  Requires MIT license to approve
image

**Comment by PragmaticPhil** [comment]
@abchatra Thanks for that - we're on it (and for OD01).

**Comment by PragmaticPhil** [comment]
Hi @abchatra . Thanks for your input and time on this - really appreciated, And soz for letting it slip through the crack. Licenses have been added to this and OD01

**Pull request merged**
