### PR TITLE
explictely set radio default power to 6

### PR DESCRIPTION
**Pull request by pelikhan**
Explicitely set randio power to 6
Fix for https://github.com/Microsoft/pxt-microbit/issues/1284

### CODE REVIEW

**Comment by abchatra** [comment]
Shouldn't the fix be in DAL?

**Comment by carlosperate** [comment]
A fix on the default radio power is coming to the DAL: https://github.com/lancaster-university/microbit-dal/pull/389

**Comment by pelikhan** [comment]
The DAL can change it's mind in the future. If we set the power on our side, we will not face this issue again.

**Comment by pelikhan** [comment]
Needs to go in v0

**Pull request merged**
