### PR TITLE
Extensions: Add EggBit

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @4tronix

### CODE REVIEW

**Comment by abchatra** [comment]
Nicely done extension.

**Review by abchatra — APPROVED** [review]

**Comment by 4tronix** [comment]
When will this extension be available for searching?

**Comment by abchatra** [comment]
Sorry there was a bug. This should be fixed in 24 hours.

**Comment by abchatra** [comment]
Thanks for letting me know.

**Pull request merged**
