### PR TITLE
Stop deleted sprites touching others

### PR DESCRIPTION
**Pull request by HelenFoster**
Fixes https://github.com/Microsoft/pxt/issues/2466

### CODE REVIEW

**Comment by pelikhan** [comment]
What other API need to use the enabled bit?

**Comment by HelenFoster** [comment]
> What other API need to use the enabled bit?

I think there isn't any at the moment (as I discussed in the issue).

**Comment by pelikhan** [comment]
Do you have projects using game APIs? We take contributions for those too :)

**Comment by HelenFoster** [comment]
> Do you have projects using game APIs? We take contributions for those too :)

I've been pondering what to do about that. This isn't really the place to discuss it, so what do you suggest?

**Comment by pelikhan** [comment]
Are you the microbit slack channel? We can use the #pxt channel there

**Pull request merged**
