### PR TITLE
add nexusbit

### PR DESCRIPTION
**Pull request by microbit-mark**
Add nexus:bit extension cc @alankrantas

### CODE REVIEW

**Comment by pelikhan** [comment]
LGTM

**Comment by alankrantas** [comment]
Hello all,

Since I'm leaving my company I have to transfer the extension to my company, and they insist using their url.

Is it possible that you can replace the urls in the approved list for me?

From https://github.com/alankrantas/pxt-Nexusbit

To https://github.com/beyond-coding-tw/nexusbot

The new extension is cloned from mine, the code are the same except some author information. and I'll delete or archive mine after it's transferred.

This is a bit urgent, and I really need your help on this.  I have to finish the transfer to officially close this job (and be able to get the next one).

**Comment by microbit-mark** [comment]
Hi @alankrantas I've also replied via support.microbit.org

Can you 
- rename as pxt-nexusbot https://github.com/beyond-coding-tw/nexusbot
- correct spellings eg https://github.com/beyond-coding-tw/nexusbot#calibrating-nexutbot and the occasional Nexus:Bit 
- update the contact details from the readme (if you're leaving the company) https://github.com/beyond-coding-tw/nexusbot#extension-author
- create a release https://github.com/beyond-coding-tw/nexusbot/releases using 'pxt bump' or when logged in to GitHub in the editor

**Comment by alankrantas** [comment]
Ok. It's done.

Nexus:bit is not a misspelled word. We corrected the rest and created a release.

**Comment by microbit-mark** [comment]
Thanks @alankrantas. I've made the updated PR here https://github.com/microsoft/pxt-microbit/pull/2315

**Comment by alankrantas** [comment]
Thanks Mark, much appreciated. :)

**Pull request merged**
