### PR TITLE
Extensions: add servobit

### PR DESCRIPTION
**Pull request by microbit-mark**
CC @4tronix

### CODE REVIEW

**Comment by abchatra** [comment]
I filed a issue to reduce the size of the png.

@pelikhan is hard coding the neopixel dependency to particular version good? 
        "neopixel": "github:microsoft/pxt-neopixel#v0.6.10"

**Comment by 4tronix** [comment]
Hi,
As seems to be normal, this has not yet been added and is not yet 
searchable. Any ideas?

Thanks,
Gareth

------ Original Message ------

**Comment by 4tronix** [comment]
I’ve fixed these issues. Can it now be released please?

Gareth

**Comment by abchatra** [comment]
@4tronix thanks for addressing the issues.

**Comment by 4tronix** [comment]
Hi,
This ServoBit Makecode extension is not showing up on Mac OS 10.15.6 
Catalina using Safari.
Even if the URL to the GitHub repository is entered it doesn't work - 
giving "not approved by Microsoft" error.

However, both the search and the URL work fine using 10.11.6 El Capitan

Please help

Thanks,
Gareth

------ Original Message ------

**Comment by abchatra** [comment]
@Gareth can you file a new issue with repro steps. Thanks!

**Comment by gareth** [comment]
> @gareth can you file a new issue with repro steps. Thanks!

I think that message was for @4tronix.

(Don't worry about the ping, it's a risk I took when I got a first-name Github account 😉 )

**Pull request merged**
