### PR TITLE
add Robobit

### PR DESCRIPTION
**Pull request by microbit-mark**
add robobit package from @4tronix

### CODE REVIEW

**Comment by microbit-mark** [comment]
Have requested a release and to update license to MIT

**Comment by microbit-mark** [comment]
See release at https://github.com/4tronix/Robobit/releases @pelikhan

**Comment by pelikhan** [comment]
The release has to be a semver  compatible version “vMAJOR.MINOR.BUILD” and match the version in pxt.json

**Comment by 4tronix** [comment]
done

------ Original Message ------

**Comment by pelikhan** [comment]
See an example of the format here: https://github.com/Microsoft/pxt-neopixel/releases/tag/v0.6.10

Our tooling (pxt bump) or the online git repo editor supports generating those.

Sorry for the hassle

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by 4tronix** [comment]
oh, you mean it needs a 'v' at the front? OK will do

Gareth

------ Original Message ------

**Comment by 4tronix** [comment]
Done now - I hope :)

Gareth

------ Original Message ------

**Comment by 4tronix** [comment]
ok. Done (took me a while to find out how)

------ Original Message ------

**Comment by pelikhan** [comment]
@4tronix  Here is an easier way to author packages: https://makecode.com/blog/github-packages

**Comment by pelikhan** [comment]
Opening new PR for this.

**Pull request closed without merging**
