### PR TITLE
Sound editor

### PR DESCRIPTION
**Pull request by microbit-josephine**
These changes have been made in conjunction with https://github.com/microsoft/pxt/pull/8504.  The introduction of the new `play sound` block provides the access point of the sound drop down field in pxt. This was work done for the https://github.com/microbit-foundation/v2/issues/864 issue. 

Most of these changes in pxt-microbit were done in music.ts to introduce the new blocks in the `sound (V2)` category (as requested in the issue https://github.com/microbit-foundation/v2/issues/829). The block also includes drop down fields for `wave types` and `interpolation` which contain png images, which fulfil the requirements of the issue https://github.com/microsoft/pxt-microbit/issues/3962, which requests drop down images. These images were simply drawn by me and converted into png images on-line. They are rather large images, and so may need to be resized.  

The rest of the changes were made in blockly.less for styling. This overrides the styling in semantic.css in pxt, as I found I couldn't render changes directly from there (probably just needed to be re built each time, but I found for the sake of testing etc it was quicker and easier to put changes in pxt-microbit). This was therefore a temporary fix I made, and so these styling changes should ultimately be put  in pxt (I think..).

### CODE REVIEW

**Comment by abchatra** [comment]
Please sign the CLA

**Comment by microbit-mark** [comment]
@microbit-josephine, can you provide descriptions for this and https://github.com/microsoft/pxt/pull/8504 so that someone who doesn't know your code and the context of the PR can easily pick it up and work with it? 

I expect this PR would reference 
https://github.com/microsoft/pxt-microbit/issues/4049 and
https://github.com/microsoft/pxt-microbit/issues/3962

**Comment by microbit-mark** [comment]
@abchatra @riknoll what are the next steps here so that we can get a an editor URL for the work here on pxt/pxt-microbit?

**Comment by abchatra** [comment]
@microbit-mark there are dependency issues with the PR in the pxt repo. Those needs to be addressed before we can produce the build. Following needs to be addressed in the pxt.

_The dependencies this change adds are pretty large -- this one alone is 81.9mb unzipped https://www.npmjs.com/package/plotly.js -- this is notably larger than all the other dependencies we have in pxt combined. I'm not certain the backend would handle things properly / it could cause issues if we tried to create a build with this in it_

**Comment by abchatra** [comment]
Who is going to address these issues?

**Comment by microbit-mark** [comment]
> Who is going to address these issues?

@abchatra I wonder if these chart libraries might be related to experiments and not actually used. Josephine has finished her contract with us, but I'll follow up on email and let you know.

**Pull request closed without merging**
