### PR TITLE
remove pause in melodies fix

### PR DESCRIPTION
**Pull request by pelikhan**
Don't pause after a tone.
- [x] v1 testing
- [x] v2 testing

### CODE REVIEW

**Comment by pelikhan** [comment]
I can't get my hand on headphones right now...

**Comment by pelikhan** [comment]
@jwunderl @aznhassan can you test that melodies sound good on v1? can't find any headphone right now.

**Comment by pelikhan** [comment]
Tested on v1 and working.

**Comment by mmoskal** [comment]
works for me on v1

**Review by mmoskal — APPROVED** [review]

**Comment by mmoskal** [comment]
@abchatra this needs to go into stable

**Comment by abchatra** [comment]
Ported to stable3.0

**Pull request merged**
