### PR TITLE
Releasing v6.0.19 (CODAL v0.2.61 release)

### PR DESCRIPTION
**Pull request by abchatra**

### CODE REVIEW

**Review by jwunderl — APPROVED** [review]

**Comment by microbit-carlos** [comment]
@abchatra any blockers to release v0.2.61 to MakeCode Live?

**Comment by abchatra** [comment]
@microbit-carlos We haven't got a chance to test on our end. If you are confident on the payload, we can release it. Let me know.

**Comment by JohnVidler** [comment]
I've been through the changes between *57 and *61, and all looks good (I've put a summary below), so I think we're OK to go live with this one.

The list looks quite long, but the actual patches are very small.

*Change Summary*

- CI additions (various)
- LED matrix power fix for standby/poweroff conditions
- Panic fixes for motion sensor malfunctions
- Fix seedRandom's return code
- General configuration flag cleanups
- Radio power level values now match DAL figures
- BLE bond count definitions relocated
- BLE name generation simplified
- BLE pairing animation sped up slightly
- Mic deep sleep shutdown enforced
- Compass calibration fixes
- Initial patches to support Clang/LLVM compilation
- Added missing pure virtual/virtual call signatures
- Added missing Newlib calls required for gcc-12 or newer builds
- Safe buffer fixes
- StreamRecording sample rate now made 'sticky' between recording events
- Max recorded audio data set to default to 50k (down from 60k)
- Touch code now correctly releases/renews pin assignments
- nrf52833 errata 78 applied
- SAADC channel config set to single sided
- Bumped nrfx to 2.1.0

**Comment by microbit-carlos** [comment]
@abchatra this PR hasn't been merged yet, any other bloquers?

**Comment by abchatra** [comment]
I merged this now. I was waiting for the final confirmation foundation as we didn't get a chance to test it. 

Can you please test tomorrow on live and ensure everything works fine?

**Pull request merged**
