### PR TITLE
add new sparkfun extensions

### PR DESCRIPTION
**Pull request by microbit-mark**
cc @andyengland521 

- [x] https://github.com/sparkfun/pxt-gator-microphone/issues
- [x] https://github.com/sparkfun/pxt-gator-soil/issues
- [x] https://github.com/sparkfun/pxt-gator-particle/issues

### CODE REVIEW

**Comment by pelikhan** [comment]
It's important to remember that extensions that use C++ will nor work in offline environments as they require a connection to the cloud for the first compilation.

**Comment by pelikhan** [comment]
@microbit-mark let's avoid bundling package reviews as any issue in of the package will block all.

**Comment by pelikhan** [comment]
I have opened bugs in all repoes.

**Comment by pelikhan** [comment]
This PR is blocked by one repo. I recommend splitting it into multiple PRs.

**Comment by microbit-mark** [comment]
Moved gator environment into it's own PR https://github.com/microsoft/pxt-microbit/pull/2326

**Pull request merged**
